tile_size = 32 #Tile size used as a base to construct the map
room_num_1 = 9 # Number of rooms for the first set of rooms to pick from
room_num_2 = 8  # Number of rooms for the second set of rooms to pick from
room_num_3 = 7  # Number of rooms for the third set of rooms to pick from

"""
    The following variable consist of a list of strings that sets the layout for the map
    that we want to draw:

    'X' -> bottom and top walls
    'P' -> player spawn.
    'F' -> floor
    'L' -> left wall
    'R' -> right wall
    'K' -> top right intersection
    'J' -> top left intersection
    'H' -> bottom left intersection
    'G' -> bottom right intersection
    'W' -> worm enemy (Basic0)
    'R' -> rabbit enemy (Basic1)
    'Q' -> crab enemy (Basic12)
    'M' -> magic range enemy (Basic2)
    'T' -> tracking enemy (Normal21)
    't' -> tracking enemy 2 (Normal22)
    'I' -> dragon enemy (Advanced2)
    'C' -> letter
    'c' -> credits
    'E' -> elevator
    'A' -> labcoat
    'B' -> glasses

    For now we're using the same sprite for each type of wall

    The floor tile in between the walls at the bottom right corner of the layout is
    were the boss or final room is going to be, placement is temporary until we decide
    how to do it
"""

moveStartPhase=[
    '            JXXXXXXXXK                                                 ',
    '            LFFFFFFFFR                                                 ',
    '            LFFFFFFFFR                                                 ',
    '            LFPFFFFFFR                                                 ',
    '            LFFFFFFFFR                                                 ',
    '            LFFFFFFFFH                                                 ',
    '            LFFFFFFFFX                                                 ',
    '            LFFFFFFFFJ                                                 ',
    '            LFFFFFFFFR                                                 ',
    '            LFFFFFFFFR                                                 ',
    '            LFFFFFFFFR                                                 ',
    '            LFFFCFFFFR                                                 ',
    '            HXXXXXXXXG                                                 ',
]

#This is the basic layout for the first level were you spawn in your room
basic_layout = [
    '                                                                       ',
    '                                                                       ',
    '                                                                       ',
    '                                                                       ',
    '                                                                       ',
    '            JXXXXXXXXK                                                 ',
    '            LFFFFFFFFR                                                 ',
    '            LFFFFFFFFR                                                 ',
    '            LFPFFFFFFR                                                 ',
    '            LFFFFFFFFRJXXXXXXXXK                                       ',
    '            LFFFFFFFFHGFFFFFFFFH                                       ',
    '            LFFFFFFFFFFFFFFFFFFD                                       ',
    '            LFFFFFFFFJKFFFFFFFFJ                                       ',
    '            LFFFFFFFFRLFFFFFFFFR                                       ',
    '            LFFFFFFFFRLFFFFFFFFR                                       ',
    '            LFFFFFFFFRLFFFFFFFFR                                       ',
    '            LFFFFFFFFRLFFFFFFFFR                                       ',
    '            HXXXXXXXXGLFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      GFFFFFFFFH                                       ',
    '                      DFFFFFFFFD                                       ',
    '                      KFFFFFFFFJ                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFH                                       ',
    '                      LFFFFFFFFD                                       ',
    '                      LFFFFFFFFJ                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      GFFFFFFFFR                                       ',
    '                      DFFFFFFFFR                                       ',
    '                      KFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFH                                       ',
    '                      LFFFFFFFFD                                       ',
    '                      LFFFFFFFFJ                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      GFFFFFFFFR                                       ',
    '                      DFFFFFFFFR                                       ',
    '                      KFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFE                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      HXXXXXXXXG                                       ',
    '                                                                       ',
    '                                                                       ',
    '                                                                       ',
    '                                                                       ',
    '                                                                       ',
    '                                                                       ',
    '                                                                       ',
    '                                                                       ',
    '                                                                       ',
    '                                                                       ',
    '                                                                       ',
]

#This is the basic layout for the rest of the levels
basic_layout_2 = [
    '                                                                       ',
    '                                                                       ',
    '                                                                       ',
    '                                                                       ',
    '                                                                       ',
    '                                                                       ',
    '                                                                       ',
    '                                                                       ',
    '                                                                       ',
    '                                                                       ',
    '                                                                       ',
    '                                                                       ',
    '                                                                       ',
    '                                                                       ',
    '                                                                       ',
    '                                                                       ',
    '                                                                       ',
    '                                                                       ',
    '                                                                       ',
    '                                                                       ',
    '                                                                       ',
    '                                                                       ',
    '                                                                       ',
    '                                                                       ',
    '                      JXXXXXXXXK                                       ',
    '                      GFFFFFFFFR                                       ',
    '                      DFPFFFFFFR                                       ',
    '                      KFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      GFFFFFFFFH                                       ',
    '                      DFFFFFFFFD                                       ',
    '                      KFFFFFFFFJ                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFH                                       ',
    '                      LFFFFFFFFD                                       ',
    '                      LFFFFFFFFJ                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      GFFFFFFFFR                                       ',
    '                      DFFFFFFFFR                                       ',
    '                      KFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFH                                       ',
    '                      LFFFFFFFFD                                       ',
    '                      LFFFFFFFFJ                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      GFFFFFFFFR                                       ',
    '                      DFFFFFFFFR                                       ',
    '                      KFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFE                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      HXXXXXXXXG                                       ',
    '                                                                       ',
    '                                                                       ',
    '                                                                       ',
    '                                                                       ',
    '                                                                       ',
    '                                                                       ',
    '                                                                       ',
    '                                                                       ',
    '                                                                       ',
    '                                                                       ',
    '                                                                       ',
]

basic_layout_3 = [
    '                                                                       ',
    '                                                                       ',
    '                                                                       ',
    '                                                                       ',
    '                                                                       ',
    '                                                                       ',
    '                                                                       ',
    '                                                                       ',
    '                                                                       ',
    '                                                                       ',
    '                      JXXXXXXXXK                                       ',
    '                      GFFFFFFFFR                                       ',
    '                      DFPFFFFFFH                                       ',
    '                      KFFFFFFFFD                                       ',
    '                      LFFFFFFFFJ                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFH                                       ',
    '                      LFFFFFFFFD                                       ',
    '                      LFFFFFFFFJ                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      GFFFFFFFFR                                       ',
    '                      DFFFFFFFFR                                       ',
    '                      KFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFH                                       ',
    '                      LFFFFFFFFD                                       ',
    '                      LFFFFFFFFJ                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFH                                       ',
    '                      LFFFFFFFFD                                       ',
    '                      LFFFFFFFFJ                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      GFFFFFFFFR                                       ',
    '                      DFFFFFFFFR                                       ',
    '                      KFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFE                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      HXXXXXXXXG                                       ',
    '                                                                       ',
    '                                                                       ',
    '                                                                       ',
    '                                                                       ',
    '                                                                       ',
    '                                                                       ',
    '                                                                       ',
    '                                                                       ',
    '                                                                       ',
    '                                                                       ',
    '                                                                       ',
]

rooms_1 = [
    [
        'XXXXX',
        'XAFBX',
        'XFFFD',
        'XFCFX',
        'XFFFX',
        'XXXXX',
    ],
    [
        'XXXXXXX',
        'XCFFFBX',
        'XAFIFFD',
        'XFQFFFX',
        'XXXXXXX',
    ],
    [
        'XXXXXXXXXXXX',
        'XCFFFFFFFFBX',
        'XFFWFFFFFFFX',
        'XFFFRFFFFFFX',
        'XFFFFMFFFFFX',
        'XFFFFFTFFFFD',
        'XFFFFFIFFFFX',
        'XFFFFFFFFFFX',
        'XFFFQFFFFFFX',
        'XAFFFFFFFFFX',
        'XXXXXXXXXXXX',
    ],
    [
        'XXXXXXXXXXXXXXXXXXXXX',
        'XFCFFFFFFFFFFFFFFFFBX',
        'XFFFFFQFFFIFFFFFFFFFD',
        'XAFFFFFFFFFFFFFFFFFFX',
        'XXXXXXXXXXXXXXXXXXXXX',
    ],
    [
        'XXXXXXXXXXXXXXXXXXXXX',
        'XFCFFFFFFFFFFFFFFFFBX',
        'XFFFFFFFFFFFFFFFFFFFX',
        'XFFFFFFFIFFFFFFFFFFFX',
        'XFFFFFFFFFFFFFFFFFFFD',
        'XFFFFFQFFFFFFFFFFFFFX',
        'XFFFFFFFFFFFFFFFFFFFX',
        'XAFFFFFFFFFFFFFFFFFFX',
        'XXXXXXXXXXXXXXXXXXXXX',
    ],
    [
        'XXXXXXXXX   XXXXXXXXX',
        'XFCFFFFBX   XFFFFFFFX',
        'XFFFFFFFXXXXXFFFFFFFX',
        'XFFFFFFFFFFFFFQFFFFFX',
        'XFFFFIFFFFFFFFFFFFFFD',
        'XFFFFFFFFFFFFFFFFFFFX',
        'XFFFFFFFXXXXXFFFFFFFX',
        'XAFFFFFFX   XFFFFFFFX',
        'XXXXXXXXX   XXXXXXXXX',
    ],
    [
        'XXXXXXXX             ',
        'XBFFFFFX             ',
        'XFFFFFFX             ',
        'XFFFFFFXXXXXXXXXXXXXX',
        'XCFFFFFFFFFFFFFFFFFFX',
        'XFFFFIFFFFQFFFFFFFFFD',
        'XFFFFFFFFFFFFFFFFFFFX',
        'XFFFFFFXXXXXXXXXXXXXX',
        'XFFFFFFX             ',
        'XFFFFFAX             ',
        'XXXXXXXX             ',
    ],
    [
        'XXXXXXXXXXXXXXXXXX ',
        'XFFFFFFFFFFFFFFFAX ',
        'XFFFFFFFFFFFFFFFFX ',
        'XFFFFFFFFFFFFFFFFX ',
        'XFFFFXXXXXXXXXXXXX ',
        'XFFFFXXXXXXXXXXXXXX',
        'XCFFFFFFFFFFFFFFFFX',
        'XFFFFFFFQFFFFFFFFFD',
        'XFFFFFFFFFFFFFFFFFX',
        'XFFFFXXXXXXXXXXXXXX',
        'XFFFFXXXXXXXXXXXXX ',
        'XFFFFFFFFFFFFFFFFX ',
        'XFFFFFFFFFFFFFFFFX ',
        'XFFFFFFFFFFFFFFFBX ',
        'XXXXXXXXXXXXXXXXXX ',
    ],
    [
        'XXXXXXXXXXXXXXXXXXXXX',
        'XFCFFFFFFFFFFFFFFFFFX',
        'XFFFFFFFFFFFFFFFFFFFD',
        'XFFFFFFFFFFFFFFFFFFFX',
        'XFFFXXXXXXXXXXXXXXXXX',
        'XFFFFFFFFFFFFFFFFFFFX',
        'XFFFFFFFFFQFFFFFFFFFX',
        'XFFFFFFFFFFFFFFFFFFFX',
        'XXXXXXXXXXXXXXXXFFFFX',
        'XBFFFFFFFFFFFFFFFFFFX',
        'XFFFFFFFFFFFFFFFFFFFX',
        'XAFFFFFFFFFFFFFFFFFFX',
        'XXXXXXXXXXXXXXXXXXXXX',
    ],
]
rooms_2 = [
    [
        'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
        'XFFFFCFFFFFXIFFFFFFFFFFFFFFFFFFFFXFFFFFFFFFXFFFFFFFFFD',
        'XFFFFFFFFFFXIFFFFFFFFFFFFFFFFFFFFXFFFFFFFFFXFFFFFFFFFX',
        'XFFFFFFFFFFXFFFFFFFFFXFFFFFFFFFFFXFFFFFFFFFXFFFFFFFFFX',
        'XFFFFFFFFFFXFFFFFFFFFXFFFFFFFFFFFXFFFFFFFFFFFFFFFFFFFX',
        'XFFFFFFFFFFXFFFFFFFFFXFFFFFFFFFFFXFFFFFFFFFXFFFFFFFFFX',
        'XIFFFFFFFFFFFFFFFFFFFXIFFFFFFFFFFFFFFFFFFFFXFFFFFFFFFX',
        'XIFFFFFFFFFFFFFFFFFFFXIFFFFFFFFFFFFFFFFFFFFXFFFFFFFFFX',
        'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    ],
    [
        'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
        'XFFFFFFFFXFFFFFFFXIFFFFFFFFFFFFFFFFFFFFFFXIFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFX',
        'XFFFCFFFFFFFRFFFFFFFFFFFFFFFFFFFRFFFFFFFFFFFFFFFFFRFFFFFFFFFFFFFFFFFFFFFFFD',
        'XFFFFFFFFXIFFFFFFFFFFFFFFFFFFXIFFFFFFFFFFFFFFFFFFFFFFXIFFFFFFFFFFFFFFFFFFFX',
        'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    ],
    [
        'XXXXXXXXXXXX',
        'XFFFFFCFFFFX',
        'XFFFFFFFFFFX',
        'XIFFFFFFFFFX',
        'XFFFFFFFFFIX',
        'XIFFFFFFFFFX',
        'XFFFFFFFFFIX',
        'XIFFFFFFFFFX',
        'XFFFFFFFFFIX',
        'XIFFFFFFFFFX',
        'XFFFFFFFFFIX',
        'XIFFFFFFFFFX',
        'XFFFFFFFFFIX',
        'XIFFFFFFFFFX',
        'XFFFFFFFFFIX',
        'XIFFFFFFFFFX',
        'XFFFFFFFFFIX',
        'XIFFFFFFFFFX',
        'XFFFFFFFFFIX',
        'XIFFFFFFFFFX',
        'XFFFFFFFFFIX',
        'XIFFFFFFFFFX',
        'XFFFFFFFFFIX',
        'XIFFFFFFFFFX',
        'XFFFFFFFFFFD',
        'XXXXXXXXXXXX',
    ],
    [
        'XXXXXXXXXXXXXXXXXXXXX', 
        'XFFFFFFFFFFFFFFFFFFFX',
        'XFFFFFFFFFFFFFFFFFFFX',
        'XFFXFFFFFFFFFFFFFFFFX',
        'XCFXFFFFFFaFFFFFFFFFD',
        'XFFXFFFFFFFFFFFFFFFFX',
        'XFFFFFFFFFFFFFFFFFFFX',
        'XFFFFFFFFFFFFFFFFFFFX',
        'XXXXXXXXXXXXXXXXXXXXX',
    ],
    [
        'XXXXXXXXXXXXXXXXXXXXX',
        'XFFFFFFFFFFFFFFFFFFFX',
        'XFFFFFFFFFFFFFFFFFFFX',
        'XCFFFFFFFFFFFFFFFFFFX',
        'XFFFFFFFFFFFFFFFFFFFD',
        'XFFFFFFFFFFFFFFFFFFFX',
        'XFFFFFFFFFFFFFFFFFFFX',
        'XFFFFFFFFFFFFFFFFFFFX',
        'XXXXXXXXXXXXXXXXXXXXX',
    ],
    [
        '    XXXXXXXXXXXXX    ',
        '    XFFFFFWFFFFFX    ',
        '    XFFFFFFFFFFFX    ',
        'XXXXXFFWFFFFFWFFXXXXX',
        'XFFFFFFFFFFFFFFFFFFFD',
        'XFFWFFFFFFFFFFFFFWFFX',
        'XFFFFFFFFFaFFFFFFFFFX',
        'XFFWFFFFFFFFFFFFFWFFX',
        'XFFFFFWFFFFFFFWFFFFFX',
        'XXXXXFFFFFFFFFFFXXXXX',
        '    XFFFFFFFFFFFX    ',
        '    XFFFFFCFFFFFX    ',
        '    XXXXXXXXXXXXX    ',
    ],
    [
        '    XXXXXXXXXXXXX    ',
        '    XFFFFFFFFFFFX    ',
        '    XFFFFFFFFFFFX    ',
        '    XFFFFFTFFFFFX    ', 
        '    XFFFFFFFFFFFX    ',
        '    XFFFFFFFFFFFX    ',
        '    XFFFFFFFFFFFX    ',
        'XXXXXFFFFFFFFFFFXXXXX',
        'XFFFFFFFFFFFFFFFFFFFD',
        'XFFFFFFFFFFFFFFFFFFFX',
        'XFFFFFFFFaFFFFFFFFFFX',
        'XFFFFFFFFFFFFFFFFFFFX',
        'XFFFFFFFFFFFFFFFFFFFX',
        'XXXXXFFFFFFFFFFFXXXXX',
        '    XFFFFFFFFFFFX    ',
        '    XFFFFFFFFFFFX    ',
        '    XFFFFFFFFFFFX    ',
        'XXXXXFFFFFFFFFFFXXXXX',
        'XIFFFFFFFFFFFFFFFFFCX',
        'XIFFFFFFFFFFFFFFFFFFX',
        'XXXXXXXXXXXXXXXXXXXXX',
    ],
    [
        'XXXXXXXXXXXXXXXXXXXXX',
        'XFCFXFFFFFFFFFFFFFFFD',
        'XFFFXFFFFFFFFFFFFFFFX',
        'XFFFXIFFFFFFFFFFFFFIX',
        'XFFFXFFXXXXXXXXXXXXXX',
        'XFFFXFFFFFFFFFFFFFFIX',
        'XFFFXFFFFFFFFFFFFFFFX',
        'XFFFXIFFFFFFFFFFFFFFX',
        'XFFFXXXXXXXXXXXXFFFFX',
        'XFFFXIFFFFFFFFFFFFFFX',
        'XFFFXFFFWFFFWFFFFFFFX',
        'XFFFFFFFWFFFWFFFFFFFX',
        'XFFFFFFFWFFFWFFFFFFFX',
        'XXXXXXXXXXXXXXXXXXXXX',
    ]
]
rooms_3 = [
    [
        'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
        'XIFFFFFFFFFFFFFFFFFFFFFFFFWFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFX',
        'XIFFFFWFFFFFFFFFFFFFFFFFFFWFFFFFFFFFFFFFFFFFFFFFFFFFFWFFFFFFFFFFFFFFFFFFFFX',
        'XFFFFFFFFFFFFFFFFFFFFFFFFFWFFFXXXXXXXXXXXXXXFFFFFFFFFFFFFFFFFFFWFFFFFFFFFFX',
        'XFFFFFFFFFFFFFFFFWFFFFFFFFWFFXFFFFFFFFFFFFFFXFFFFFFFFFFFFFFFFFFFFFFFFFFFFFX',
        'XFFFFFFFFFFFFFFFFFFFFFFFFFWFXFFFFFFFWFFFFFFFFXFFFFFFFFFFFFFFFFFFFFFFFFWFFFX',
        'XFFFFFWFFFFFFFFFFFWFFFFFFFWXFFFFFFFFFFFFFFFFFFXFFFFFFFFFWFFFFFFFFFFFFFFFFFX',
        'XFFFFFFFFFFFFFFFFFFFFFFFFFXFFFFFFFFFFFFFFFFFFFIXFFFFFFFFFFFFFFFFFFFFFFFFFFX',
        'XFFFFFFFFFFFFWFFFFFFFFFFFFFFFFFFFFFFCFFFFFFFFFIXFFFFFFFFFFFFFFFFWFFFFFFFFFD',
        'XFFFFFFFFFFFFFFFFFFFFFFFFFXFFFFFFFFFFFFFFFFFFFIXFFFFFFFFFFFFFFFFFFFFFFFFFFX',
        'XIFFFFFFFFFFFFFFFFWFFFFFFFWXFFFFFFFFFFFFFFFFFFXFFFFFFFFFWFFFFFFFFFFFFFFFFFX',
        'XFFFFFFFFWFFFFFFFFFFFFFFFFWFXFFFFFFFWFFFFFFFFXFFFFFFFFFFFFFFFFFFFFFFFFWFFFX',
        'XIFFFFFFFFFFFFFFFFFFFFFFFFFFFXFFFFFFFFFFFFFFXFFFFFWFFFFFFFFFFFFFFFFFFFFFFFX',
        'XIFFFFFFFFFFFFFFFWFFFFFFFFFFFFXXXXXXXXXXXXXXFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFX',
        'XIFFFFFFFFFFFFFFFFFFFFFFFFWFFFFFFFFFFFFFFFFFFFFFFFFFFFWFFFFFFFFFWFFFFFFFFFX',
        'XIFFFFFFFFFFWFFFFFFFFFFFFFWFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFX',
        'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    ],
    [
        'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
        'XIFFFFFFFFFFFFFFFFFFFFCFFFWFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFX',
        'XIFFFFWFFFFFFFFFFFFFFFFFFFWFFFFFFFFFFFFFFFFFFFFFFFFFFWFFFFFFFFFFFFFFFFFFFFX',
        'XFFFFFFFFFFFFFFFFFFFFFFFFFWFFFXXXXXXXXXXXXXXFFFFFFFFFFFFFFFFFFFWFFFFFFFFFFX',
        'XFFFFFFFFFFFFFFFFWFFFFFFFFWFFXFFFFFFFFFFFFFFXFFFFFFFFFFFFFFFFFFFFFFFFFFFFFX',
        'XFFFFFFFFFFFFFFFFFFFFFFFFFWFXFFFFFFFWFFFFFFFFXFFFFFFFFFFFFFFFFFFFFFFFFWFFFX',
        'XFFFFFWFFFFFFFFFFFWFFFFFFFWXFFFFFFFFFFFFFFFFFFXFFFFFFFFFWFFFFFFFFFFFFFFFFFX',
        'XFFFFFFFFFFFFFFFFFFFFFFFFFXFFFFFFFFFFFFFFFFFFFIXFFFFFFFFFFFFFFFFFFFFFFFFFFX',
        'XFFFFFFFFFFFFWFFFFFFFFFFFFFFFFFFFFFFWFFFFFFFFFIXFFFFFFFFFFFFFFFFWFFFFFFFFFD',
        'XFFFFFFFFFFFFFFFFFFFFFFFFFXFFFFFFFFFFFFFFFFFFFIXFFFFFFFFFFFFFFFFFFFFFFFFFFX',
        'XIFFFFFFFFFFFFFFFFWFFFFFFFWXFFFFFFFFFFFFFFFFFFXFFFFFFFFFWFFFFFFFFFFFFFFFFFX',
        'XFFFFFFFFWFFFFFFFFFFFFFFFFWFXFFFFFFFWFFFFFFFFXFFFFFFFFFFFFFFFFFFFFFFFFWFFFX',
        'XIFFFFFFFFFFFFFFFFFFFFFFFFFFFXFFFFFFFFFFFFFFXFFFFFWFFFFFFFFFFFFFFFFFFFFFFFX',
        'XIFFFFFFFFFFFFFFFWFFFFFFFFFFFFXXXXXXXXXXXXXXFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFX',
        'XIFFFFFFFFFFFFFFFFFFFFFFFFWFFFFFFFFFFFFFFFFFFFFFFFFFFFWFFFFFFFFFWFFFFFFFFFX',
        'XIFFFFFFFFFFWFFFFFFFFFFFFFWFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFX',
        'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    ],
    [
        'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
        'XXXXXXXWFFFFFFFFFFFXXXFFFFFFFFFFFFFXXXXXXXXXXXFFFFWXXXXFFFFFFFFFFFFFFFFFXXX',
        'XXXXWXXXXXXXXXXFXXFXXXFXXXXXXXXXXXFFFFFFFFFXXXFXXXXXXXXFXXXFXXXXXXXXXXXFXXX',
        'XXXXFXXXXXFFFFFFXXFFFFFFFFFWFFFFFFFXXXXXXXFXXXFXXXFFFFFFXXXXXXXXXXXXXXXFXXX',
        'XXXXFFFFFFFXXXXXXXXXXFXXXXXXXXXXXXXXFFCXXXFXXXFXXXFXXXXXXFFFFFFFFFFFXXXFFFD',
        'XXWXXXXXXXXXXXXFFFFFFFFFFXXFFFFFFXXXFXXXXXFXXXFFFFFXXXXXXFXXXXXXFXXFXXXFXXX',
        'XXFFFFFFFFFXXXXFXXXXXFXXFXXFXXXXFXXXFXXXXXFXXXFXXXFXXXXXXFXXXWFXFXXFXXXFXXX',
        'XXXXXXXXXXFFFFFFXWFFFFXXFFFFXXXXFFFFFXXXXFFFFFXXXFFFFFFFFFXXXXFFFXXFFFFFXXX',
        'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    ],
    [
        'XXXXXXXXXXXXX        XXXXXX          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
        'XFFFFFFFFFFFX       XFFWFFX         XFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFRFFFFXXX',
        'XFFFFXXXFFFFX    XXXFFFFFFXXXXXX   XFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFXXX',
        'XFFFRX XFFFFXXXXXFFFFFFFFFFFFFCX  XIFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFXXX',
        'XFFFFX XXXFFFFFFFFFIXXXXXXXXXXXX  XIFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFD',
        'XFFFRX    XXXXXXXXXXX             XIFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFXXX',
        'XFFFFXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXFFFFWFFFFFFFFFFFFFFFFFFWFFFFFFFFFFFFFXXX',
        'XFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFWFFFFFFFFFFFFXXX',
        'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    ],
    [
        'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
        'XFFFFIFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFXXX',
        'XFFFFIFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFXXX',
        'XFXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXFXXXXXXXXXXXXXXXXXXXFFFFFFFFFFFFFFFFFFFXXX',
        'XWX                             XFX                 XFFFFFFFFFFaFFFFFFFFXXX',
        'XXX                             XXX                 XFFFFFFFFFFFFFFFFFFFXXX',
        '                                                    XFFFFFFFFFFFFFFFFFFFXXX',
        'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXFFFFFFFFFFFFFFFFFFFXXX',
        'XFWFFFFFFFFWFFFFFFFFFFFFFFFFFFWFFFIFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFXXX',
        'XFFWFFFFFFFWFFFFFFFFFFFFFFFFFFWFFFFIFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFXXX',
        'XFFWFFFFFFFFFFFFFFFWFFFFFFFFFFFFFFFIFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFD',
        'XFWFFFFFFFFFFFFFFFFWFFFFFFFFFFFFFFIFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFXXX',
        'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXFFFFFFFFFFFFFFFFFFFXXX',
        '                                                    XFFFFFFFFFFFFFFFFFFFXXX',
        '                                                    XFFFFFFFFFFaFFFFFFFFXXX',
        'XXX                              XXX                XFFFFFFFFFFFFFFFFFFFXXX',
        'XCX                              XFX                XFFFFFFFFFFFFFFFFFFFXXX',
        'XFXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXFXXXXXXXXXXXXXXXXXXFFFFFFFFFFFFFFFFFFFXXX',
        'XIFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFXXX',
        'XIFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFXXX',
        'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    ],
    [
        'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
        'XFFFFIFFFFFFFFFFFFFFFFFFFFXIFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFXXX',
        'XFFFFIFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFXIFFFFFFFFFFFFFFFFFFFFFXXX',
        'XFFXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXFFXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXFFXXX',
        'XFFX                                XFFX                             XFFXXX',
        'XFFX                                XXXX                             XFFXXX',
        'XFFX                                                                 XFFXXX',
        'XFFXXXXXXXXXXXXXXXXXXXXXXXXXXX                XXXXXXXXXXXXXXXXXXXXXXXXFFXXX',
        'XFWFFFFFFFFFFFFFFFFFFFFFFFFFFX                XFFFFFFFFFFFFFFFFFFFFFFFFFXXX',
        'XFFFFFFFFFFFFFFFFaFFFFFFFFFFFX                XFFFFFFFFFaFFFFFFFFFFFFFFFXXX',
        'XFFFFFFFFFFFFFFFFFFFFFFFFFFFCX                XFFFFFFFFFFFFFFFFFFFFFFFFFFFD',
        'XFFFFFFFFFFFFFFFFFFFFFFFFFFFFX                XFFFFFFFFFFFFFFFFFFFFFFFFFXXX',
        'XFFXXXXXXXXXXXXXXXXXXXXXXXXXXX                XXXXXXXXXXXXXXXXXXXXXXXXFFXXX',
        'XFFX                                                                 XFFXXX',      #METER CREDITOS
        'XFFX                                                                 XFFXXX',
        'XFFX                                                                 XFFXXX',
        'XFFXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXFFXXX',
        'XIFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFWFFFWFFFFFFFFFFFFFFFWFFFFFFFFFFFFFFFFXXX',
        'XIFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFWFFFFFFFFFFFFFFFXXX',
        'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    ],
    [
        'XXXXXXXXXXXXXXXXXXXXX    XXXXXXXXXXXXXXXXXXXXX    XXXXXXXXXXXXXXXXXXXXX', 
        'XFFFFFFFFFFFFFFFFFFFX    XFFFFFFFFFFFFFFFFFFFX    XFFFFFFFFFFFFFFFFFFFX',
        'XFFFFFFFFFFFFFFFFFFFX    XFFFFFFFFFFFFFFFFFFFX    XFFFFFaFFFFFFFFFFFFFX',
        'XFFXFFFFFFFFFFFFFFFFXXXXXXFFFFFFFFaFFFFFFFFFFXXXXXXFFFFFFFFFFFFFFFFFFFX',
        'XCFXFFFFFFaFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFD',
        'XFFXFFFFFFFFFFFFFFFFXXXXXXFFFFFFFFFFFaFFFFFFFXXXXXXFFFFFFFFFFFFFFFFFFFX',
        'XFFFFFFFFFFFFFFFFFFFX    XFFFFFFFFFFFFFFFFFFFX    XFFFFFFFFFFFFFFaFFFFX',
        'XFFFFFFFFFFFFFFFFFFFX    XFFFFFFFFFFFFFFFFFFFX    XFFFFFFFFFFFFFFFFFFFX',
        'XXXXXXXXXXXXXXXXXXXXX    XXXXXXXXXXXXXXXXXXXXX    XXXXXXXXXXXXXXXXXXXXX', 
    ]
]