tile_size = 32 #Tile size used as a base to construct the map
room_num = 7 #Number of rooms to pick from

"""
    The following variable consist of a list of strings that sets the layout for the map
    that we want to draw:

    'X' -> bottom and top walls
    'P' -> player spawn.
    'F' -> floor
    'L' -> left wall
    'R' -> right wall
    'K' -> top right intersection
    'J' -> top left intersection
    'H' -> bottom left intersection
    'G' -> bottom right intersection
    'W' -> worm enemy (Basic0)
    'R' -> rabbit enemy (Basic1)
    'M' -> magic range enemy (Basic2)
    'T' -> tracking enemy (Normal2)
    'D' -> dragon enemy (Advanced2)

    For now we're using the same sprite for each type of wall

    The floor tile in between the walls at the bottom right corner of the layout is
    were the boss or final room is going to be, placement is temporary until we decide
    how to do it
"""

#This is the basic layout for the first level were you spawn in your room
basic_layout = [
    '                                                                       ',
    '            JXXXXXXXXK                                                 ',
    '            LFFFFFFFFR                                                 ',
    '            LFFFFFFFFR                                                 ',
    '            LFPFFFFFFR                                                 ',
    '            LFFFFFFFFRJXXXXXXXXK                                       ',
    '            LFFFFFFFFHGFFFFFFFFH                                       ',
    '            LFFFFFFFFFFFFFFFFFFD                                       ',
    '            LFFFFFFFFJKFFFFFFFFJ                                       ',
    '            LFFFFFFFFRLFFFFFFFFR                                       ',
    '            LFFFFFFFFRLFFFFFFFFR                                       ',
    '            LFFFFFFFFRLFFFFFFFFR                                       ',
    '            LFFFFFFFFRLFFFFFFFFR                                       ',
    '            HXXXXXXXXGLFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      GFFFFFFFFH                                       ',
    '                      DFFFFFFFFD                                       ',
    '                      KFFFFFFFFJ                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFH                                       ',
    '                      LFFFFFFFFD                                       ',
    '                      LFFFFFFFFJ                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      GFFFFFFFFR                                       ',
    '                      DFFFFFFFFR                                       ',
    '                      KFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFH                                       ',
    '                      LFFFFFFFFD                                       ',
    '                      LFFFFFFFFJ                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      GFFFFFFFFR                                       ',
    '                      DFFFFFFFFR                                       ',
    '                      KFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFF                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      HXXXXXXXXG                                       ',
    '                                                                       ',
    '                                                                       ',
    '                                                                       ',
    '                                                                       ',
    '                                                                       ',
    '                                                                       ',
    '                                                                       ',
    '                                                                       ',
    '                                                                       ',
    '                                                                       ',
    '                                                                       ',
]

#This is the basic layout for the rest of the levels
basic_layout_2 = [
    '                                                                       ',
    '                                                                       ',
    '                                                                       ',
    '                                                                       ',
    '                                                                       ',
    '                      JXXXXXXXXK                                       ',
    '                      GFFFFFFFFR                                       ',
    '                      DFPFFFFFFR                                       ',
    '                      KFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      GFFFFFFFFH                                       ',
    '                      DFFFFFFFFD                                       ',
    '                      KFFFFFFFFJ                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFH                                       ',
    '                      LFFFFFFFFD                                       ',
    '                      LFFFFFFFFJ                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      GFFFFFFFFR                                       ',
    '                      DFFFFFFFFR                                       ',
    '                      KFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFH                                       ',
    '                      LFFFFFFFFD                                       ',
    '                      LFFFFFFFFJ                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      GFFFFFFFFR                                       ',
    '                      DFFFFFFFFR                                       ',
    '                      KFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFF                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      HXXXXXXXXG                                       ',
    '                                                                       ',
    '                                                                       ',
    '                                                                       ',
    '                                                                       ',
    '                                                                       ',
    '                                                                       ',
    '                                                                       ',
    '                                                                       ',
    '                                                                       ',
    '                                                                       ',
    '                                                                       ',
]

rooms = [
    [
        'XXXXX',
        'XFFFX',
        'XFFFD',
        'XFFFX',
        'XFFFX',
        'XXXXX',
    ],
    [
        'XXXXXXX',
        'XFFFFFX',
        'XFFFFFD',
        'XFFFFFX',
        'XXXXXXX',
    ],
    [
        'XXXXXXXXXXXX',
        'XFFFFFFFFFFX',
        'XFFWFFFFFFFX',
        'XFFFRFFFFFFX',
        'XFFFFMFFFFFX',
        'XFFFFFTFFFFD',
        'XFFFFFFFFFFX',
        'XFFFFFFFFFFX',
        'XFFFFFFFFFFX',
        'XFFFFFFFFFFX',
        'XXXXXXXXXXXX',
    ],
    [
        'XXXXXXXXXXXXXXXXXXXXX',
        'XFFFFFFFFFFFFFFFFFFFX',
        'XFFFFFFFFFFFFFFFFFFFD',
        'XFFFFFFFFFFFFFFFFFFFX',
        'XXXXXXXXXXXXXXXXXXXXX',
    ],
    [
        'XXXXXXXXXXXXXXXXXXXXX',
        'XFFFFFFFFFFFFFFFFFFFX',
        'XFFFFFFFFFFFFFFFFFFFX',
        'XFFFFFFFFFFFFFFFFFFFX',
        'XFFFFFFFFFFFFFFFFFFFD',
        'XFFFFFFFFFFFFFFFFFFFX',
        'XFFFFFFFFFFFFFFFFFFFX',
        'XFFFFFFFFFFFFFFFFFFFX',
        'XXXXXXXXXXXXXXXXXXXXX',
    ],
    [
        'XXXXXXXXX   XXXXXXXXX',
        'XFFFFFFFX   XFFFFFFFX',
        'XFFFFFFFXXXXXFFFFFFFX',
        'XFFFFFFFFFFFFFFFFFFFX',
        'XFFFFFFFFFFFFFFFFFFFD',
        'XFFFFFFFFFFFFFFFFFFFX',
        'XFFFFFFFXXXXXFFFFFFFX',
        'XFFFFFFFX   XFFFFFFFX',
        'XXXXXXXXX   XXXXXXXXX',
    ],
    [
        'XXXXXXXX             ',
        'XFFFFFFX             ',
        'XFFFFFFX             ',
        'XFFFFFFXXXXXXXXXXXXXX',
        'XFFFFFFFFFFFFFFFFFFFX',
        'XFFFFFFFFFFFFFFFFFFFD',
        'XFFFFFFFFFFFFFFFFFFFX',
        'XFFFFFFXXXXXXXXXXXXXX',
        'XFFFFFFX             ',
        'XFFFFFFX             ',
        'XXXXXXXX             ',
    ],
]
