tile_size = 32 #Tile size used as a base to construct the map

"""
    The following variable consist of a list of strings that sets the layout for the map
    that we want to draw:

    'X' -> bottom and top walls
    'P' -> player spawn.
    'F' -> floor
    'L' -> left wall
    'R' -> right wall
    'K' -> top right intersection
    'J' -> top left intersection
    'H' -> bottom left intersection
    'G' -> bottom right intersection
    'W' -> worm enemy (Basic0)
    'R' -> rabbit enemy (Basic1)
    'Q' -> crab enemy (Basic12)
    'M' -> magic range enemy (Basic2)
    'T' -> tracking enemy (Normal21)
    't' -> tracking enemy 2 (Normal22)
    'I' -> dragon enemy (Advanced2)
    'C' -> letter
    'c' -> credits
    'E' -> elevator
    'A' -> labcoat
    'B' -> glasses
"""

moveStartPhase=[
    '            JXXXXXXXXK                                                 ',
    '            LFFFFFFFFR                                                 ',
    '            LFFFFFFFFR                                                 ',
    '            LFPFFFFFFR                                                 ',
    '            LFFFFFFFFR                                                 ',
    '            LFFFFFFFFH                                                 ',
    '            LFFFFFFFFX                                                 ',
    '            LFFFFFFFFJ                                                 ',
    '            LFFFFFFFFR                                                 ',
    '            LFFFFFFFFR                                                 ',
    '            LFFFFFFFFR                                                 ',
    '            LFFFCFFFFR                                                 ',
    '            HXXXXXXXXG                                                 ',
]

#This is the basic layout for the first level were you spawn in your room
basic_layout = [
    '                                                                       ',
    '                                                                       ',
    '                                                                       ',
    '                                                                       ',
    '                                                                       ',
    '            JXXXXXXXXK                                                 ',
    '            LFFFFFFFFR                                                 ',
    '            LFFFFFFFFR                                                 ',
    '            LFPFFFFFFR                                                 ',
    '            LFFFFFFFFRJXXXXXXXXK                                       ',
    '            LFFFFFFFFHGFFFFFFFFH                                       ',
    '            LFFFFFFFFFFFFFFFFFFD                                       ',
    '            LFFFFFFFFJKFFFFFFFFJ                                       ',
    '            LFFFFFFFFRLFFFFFFFFR                                       ',
    '            LFFFFFFFFRLFFFFFFFFR                                       ',
    '            LFFFFFFFFRLFFFFFFFFR                                       ',
    '            LFFFFFFFFRLFFFFFFFFR                                       ',
    '            HXXXXXXXXGLFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      GFFFFFFFFH                                       ',
    '                      DFFFFFFFFD                                       ',
    '                      KFFFFFFFFJ                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFH                                       ',
    '                      LFFFFFFFFD                                       ',
    '                      LFFFFFFFFJ                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      GFFFFFFFFR                                       ',
    '                      DFFFFFFFFR                                       ',
    '                      KFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFH                                       ',
    '                      LFFFFFFFFD                                       ',
    '                      LFFFFFFFFJ                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      GFFFFFFFFR                                       ',
    '                      DFFFFFFFFR                                       ',
    '                      KFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFE                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      LFFFFFFFFR                                       ',
    '                      HXXXXXXXXG                                       ',
    '                                                                       ',
    '                                                                       ',
    '                                                                       ',
    '                                                                       ',
    '                                                                       ',
    '                                                                       ',
    '                                                                       ',
    '                                                                       ',
    '                                                                       ',
    '                                                                       ',
    '                                                                       ',
]

#This is the basic layout for the rest of the levels
basic_layout_2 = [
    '                                                                                                                                                                    ',
    '                                                                                                                                                                    ',
    '                                                                                                                                                                    ',
    '                                                                                                                                                                    ',
    '                                                                                                                                                                    ',
    '                                                                                                                                                                    ',
    '                                                                                                                                                                    ',
    '                                                                                                                                                                    ',
    '                                                                                                                                                                    ',
    '                                                                                                                                                                    ',
    '                                                                                                                                                                    ',
    '                                                                                                                                                                    ',
    '                                                                                                                                                                    ',
    '                                                                                                                                                                    ',
    '                                                                                                                                                                    ',
    '                                                                                                                                                                    ',
    '                                                                                                                                                                    ',
    '                                                                                                                                                                    ',
    '                                                                                                                                                                    ',
    '                                                                                                                                                                    ',
    '                                                                                                                                                                    ',
    '                                                                                                                                                                    ',
    '                                                                                                                                                                    ',
    '                                                                                                                                                                    ',
    '                                                                                                                                                                    ',
    '                                                                             JXXXXXXXXK                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             DFPFFFFFFD                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             DFFFFFFFFD                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             DFFFFFFFFD                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             DFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFE                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             HXXXXXXXXG                                                                             ',
    '                                                                                                                                                                    ',
    '                                                                                                                                                                    ',
    '                                                                                                                                                                    ',
    '                                                                                                                                                                    ',
    '                                                                                                                                                                    ',
    '                                                                                                                                                                    ',
    '                                                                                                                                                                    ',
    '                                                                                                                                                                    ',
    '                                                                                                                                                                    ',
    '                                                                                                                                                                    ',
    '                                                                                                                                                                    ',
]

basic_layout_3 = [
    '                                                                                                                                                                    ',
    '                                                                                                                                                                    ',
    '                                                                                                                                                                    ',
    '                                                                                                                                                                    ',
    '                                                                                                                                                                    ',
    '                                                                                                                                                                    ',
    '                                                                                                                                                                    ',
    '                                                                                                                                                                    ',
    '                                                                                                                                                                    ',
    '                                                                                                                                                                    ',
    '                                                                                                                                                                    ',
    '                                                                                                                                                                    ',
    '                                                                                                                                                                    ',
    '                                                                             JXXXXXXXXK                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             DFPFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFD                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFD                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             DFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFD                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFD                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             DFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFE                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             HXXXXXXXXG                                                                             ',
    '                                                                                                                                                                    ',
    '                                                                                                                                                                    ',
    '                                                                                                                                                                    ',
    '                                                                                                                                                                    ',
    '                                                                                                                                                                    ',
    '                                                                                                                                                                    ',
    '                                                                                                                                                                    ',
    '                                                                                                                                                                    ',
    '                                                                                                                                                                    ',
    '                                                                                                                                                                    ',
    '                                                                                                                                                                    ',
]

rooms_1 = [
    [
        'XXXXXXXXXXXX  XXXXXX',
        'XAFBFFFFFFFXXXXFFFFX',
        'XFFFFWFFFFFFFFFFFFFD',
        'XFCFFFFFFFFFWFFFFFFX',
        'XFFFWFFFFFFFFFFFFFFX',
        'XFFFFFFFFFFXXXXFFFFX',
        'XXXXXXXXXXXX  XXXXXX',
    ],
    [
        'XXXXXXXXXXXXXXXXXXXX',
        'XFAFFFFFFFFFFFFFFFFX',
        'XFFFFFFFFFFFFFFFFFFX',
        'XFFFFFFFWWFFFFFFFFFX',
        'XFFFFFFFFFFFFFQFFFFX',
        'XFFFFFFFFFFFFFFFFFFX',
        'XXXXXXXXFFXXXXXXXXXX',
        '       XFFX         ',
        'XXXXXXXXFFXXXXXXXXXX',
        'XFFFFFFFFFFFFFFFFFFX',
        'XFCFFFFFFFFFFFFFFFFD',
        'XFFFFFFFFFFFFFFQFFFX',
        'XFFFFFFFFFFFFFFFFFFX',
        'XXXXXXXXXFFXXXXXXXXX',
        '        XFFX        ',
        'XXXXXXXXXFFXXXXXXXXX',
        'XFFFFFFFFFFFFFFFFFFX',
        'XFWFFFFFFFFFFFFFFFFX',
        'XFFFFFFFFFFFFFFQFFFX',
        'XBFFFWFFFFFFFFFFFFFX',
        'XXXXXXXXXXXXXXXXXXXX',
    ],
    [
        'XXXXXXXXXXXX',
        'XCFFFFFFFFBX',
        'XFFFFFFFFFFX',
        'XFFFFFFFRFFX',
        'XFFFFWFFFFFX',
        'XFFFFFFFFFFD',
        'XFFFFFFFFFFX',
        'XFFFFWFFFFFX',
        'XFFFQFFFFFFX',
        'XAFFFFFFFFFX',
        'XXXXXXXXXXXX',
    ],
    [
        'XXXXXXXXXXXXXXXXXXXXX',
        'XFCFFFFFFFFFFFFWFFFBX',
        'XFFFFFQFFFFFFFFFFFFFD',
        'XAFFFFFFFFWFFFFFFFFFX',
        'XXXXXXXXXXXXXXXXXXXXX',
    ],
    [
        'XXXXXXXXXXXXXXXXXXXXX',
        'XFCFFWFFFFFFFFWFFFFBX',
        'XFFFFFFFFFRFFFFFFFFFX',
        'XFFFFFFFWFFFFFFFFFFFX',
        'XFFFFFFFFFFFFFFFFFFFD',
        'XFFFFFWFFFFFFWFFFFFFX',
        'XFFFFFFFFFFRFFFFFFFFX',
        'XAFFFFFFFFFFFFFFFFFFX',
        'XXXXXXXXXXXXXXXXXXXXX',
    ],
    [
        'XXXXXXXXX   XXXXXXXXX',
        'XFCFFFFBX   XFFFFFFFX',
        'XFFFFFFFXXXXXFFFFWFFX',
        'XFFFFFFFRFFFFFFFFFFFX',
        'XFFFFFFFFFFFFFFFFFFFX',
        'XFFFFFQFFFFFFFFFFFFFD',
        'XFFFFFFFFFFFFFRFFFFFX',
        'XFFFFFFFFFWFFFFFFWFFX',
        'XFFFFFFFXXXXXFFFFFFFX',
        'XAFFFFFFX   XFFFFFFFX',
        'XXXXXXXXX   XXXXXXXXX',
    ],
    [
        'XXXXXXXX                ',
        'XBFFFFFX                ',
        'XFFFWFFX                ',
        'XFFFFFFXXXXXXXXXXXXXXXXX',
        'XCFFFFFFFFFWFFFFFFFFFFFX',
        'XFFFFFFFFFFFFFFFFFFFFFFX',
        'XFFFFFFFFFRFFFFFFFFFFFFD',
        'XFFFFFFFFFFFFFFFFFFFFFFX',
        'XFFFFFFFFFFFFFFFFWFFFFFX',
        'XFFFFFFXXXXXXXXXXXXXXXXX',
        'XFFFFFFX                ',
        'XFFFFFAX                ',
        'XXXXXXXX                ',
    ],
    [
        'XXXXXXXXXXXXXXXXXX ',
        'XFFFFFFFWFFFFFFFAX ',
        'XFFFFFFFFFFFFFFFFX ',
        'XFFFFFFFFFFQFFFFFX ',
        'XFFFFXXXXXXXXXXXXX ',
        'XFFFFXXXXXXXXXXXXXX',
        'XCFFFFFFFFFFFFFFFFX',
        'XFFFFFFFQFFFFFFFFFD',
        'XFFFFFFFFFFFFFFFFFX',
        'XFFFFXXXXXXXXXXXXXX',
        'XFFFFXXXXXXXXXXXXX ',
        'XFFFFFFFFFFFFFFFFX ',
        'XFFFFFFFFFQFFFFFFX ',
        'XFFFFFFFFFFFFFFFFX ',
        'XFFFFFFFWFFFFFFFBX ',
        'XXXXXXXXXXXXXXXXXX ',
    ],
    [
        'XXXXXXXXXXXXXXXXXXXXX',
        'XFFFFFFFFFFFFFFFFFFFX',
        'XFFFFFFFFFFFFFFFFFFFD',
        'XFQFFFFFFFFFFFFFFFFFX',
        'XFFFFFFFFFFFFFFFFFFFX',
        'XFFFXXXXXXXXXXXXXXXXX',
        'XFFFWFFFFFFFFFFFFFFFX',
        'XFFFFFFFFFFFFFFFFFFFX',
        'XFFFFRFFFFFFFFFFFFFFX',
        'XFFFFFFFFFFFFFFFFFFFX',
        'XFFFFFFWFFFFFFFFFFFFX',
        'XXXXXXXXXXXXXXXXFFFFX',
        'XCFFFWFFFFFFFFFFFFFFX',
        'XFFFFFFFFFFFFWFFFFFFX',
        'XAFFFFFFFWFFFFFFFFFFX',
        'XXXXXXXXXXXXXXXXXXXXX',
    ],
]
rooms_2 = [
    [
        'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
        'XFFFFCFFFFFXIFFFFFFFFFFFFFFFFFFFFXFFFFFFFFFXFFFFFFFFFD',
        'XFFFFFFFFFFXIFFFFFFFFFFFFFFFFFFFFXFFFFFFFFFXFFFFFFFFFX',
        'XFFFFFFFFFFXFFFFFFFFFXFFFFFFFFFFFXFFFFFFFFFXFFFFFFFFFX',
        'XFFFFFFFFFFXFFFFFFFFFXFFFFFFFFFFFXFFFFFFFFFFFFFFFFFFFX',
        'XFFFFFFFFFFXFFFFFFFFFXFFFFFFFFFFFXFFFFFFFFFXFFFFFFFFFX',
        'XIFFFFFFFFFFFFFFFFFFFXIFFFFFFFFFFFFFFFFFFFFXFFFFFFFFFX',
        'XIFFFFFFFFFFFFFFFFFFFXIFFFFFFFFFFFFFFFFFFFFXFFFFFFFFFX',
        'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    ],
    [
        'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
        'XFFFFFFFFXFFFFFFFXIFFFFFFFFFFFFFFFFFFFFFFXIFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFX',
        'XFFFCFFFFFFFRFFFFFFFFFFFFFFFFFFFRFFFFFFFFFFFFFFFFFRFFFFFFFFFFFFFFFFFFFFFFFD',
        'XFFFFFFFFXIFFFFFFFFFFFFFFFFFFXIFFFFFFFFFFFFFFFFFFFFFFXIFFFFFFFFFFFFFFFFFFFX',
        'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    ],
    [
        'XXXXXXXXXXXX',
        'XFFFFFCFFFFX',
        'XFFFFFFFFFFX',
        'XIFFFFFFFFFX',
        'XFFFFFFFFFIX',
        'XIFFFFFFFFFX',
        'XFFFFFFFFFIX',
        'XIFFFFFFFFFX',
        'XFFFFFFFFFIX',
        'XIFFFFFFFFFX',
        'XFFFFFFFFFIX',
        'XIFFFFFFFFFX',
        'XFFFFFFFFFIX',
        'XIFFFFFFFFFX',
        'XFFFFFFFFFIX',
        'XIFFFFFFFFFX',
        'XFFFFFFFFFIX',
        'XIFFFFFFFFFX',
        'XFFFFFFFFFIX',
        'XIFFFFFFFFFX',
        'XFFFFFFFFFIX',
        'XIFFFFFFFFFX',
        'XFFFFFFFFFIX',
        'XIFFFFFFFFFX',
        'XFFFFFFFFFFD',
        'XXXXXXXXXXXX',
    ],
    [
        'XXXXXXXXXXXXXXXXXXXXX', 
        'XFFFFFFFFFFFFFFFFFFFX',
        'XFFFFFFFFFFFFFFFFFFFX',
        'XFFXFFFFFFFFFFFFFFFFX',
        'XCFXFFFFFFaFFFFFFFFFD',
        'XFFXFFFFFFFFFFFFFFFFX',
        'XFFFFFFFFFFFFFFFFFFFX',
        'XFFFFFFFFFFFFFFFFFFFX',
        'XXXXXXXXXXXXXXXXXXXXX',
    ],
    [
        'XXXXXXXXXXXXXXXXXXXXX',
        'XFFFFFFFFFFFFFFFFFFFX',
        'XFFFFFFFFFFFFFFFFFFFX',
        'XCFFFFFFFFFFFFFFFFFFX',
        'XFFFFFFFFFFFFFFFFFFFD',
        'XFFFFFFFFFFFFFFFFFFFX',
        'XFFFFFFFFFFFFFFFFFFFX',
        'XFFFFFFFFFFFFFFFFFFFX',
        'XXXXXXXXXXXXXXXXXXXXX',
    ],
    [
        '    XXXXXXXXXXXXX    ',
        '    XFFFFFWFFFFFX    ',
        '    XFFFFFFFFFFFX    ',
        'XXXXXFFWFFFFFWFFXXXXX',
        'XFFFFFFFFFFFFFFFFFFFD',
        'XFFWFFFFFFFFFFFFFWFFX',
        'XFFFFFFFFFaFFFFFFFFFX',
        'XFFWFFFFFFFFFFFFFWFFX',
        'XFFFFFWFFFFFFFWFFFFFX',
        'XXXXXFFFFFFFFFFFXXXXX',
        '    XFFFFFFFFFFFX    ',
        '    XFFFFFCFFFFFX    ',
        '    XXXXXXXXXXXXX    ',
    ],
    [
        '    XXXXXXXXXXXXX    ',
        '    XFFFFFFFFFFFX    ',
        '    XFFFFFFFFFFFX    ',
        '    XFFFFFTFFFFFX    ', 
        '    XFFFFFFFFFFFX    ',
        '    XFFFFFFFFFFFX    ',
        '    XFFFFFFFFFFFX    ',
        'XXXXXFFFFFFFFFFFXXXXX',
        'XFFFFFFFFFFFFFFFFFFFD',
        'XFFFFFFFFFFFFFFFFFFFX',
        'XFFFFFFFFaFFFFFFFFFFX',
        'XFFFFFFFFFFFFFFFFFFFX',
        'XFFFFFFFFFFFFFFFFFFFX',
        'XXXXXFFFFFFFFFFFXXXXX',
        '    XFFFFFFFFFFFX    ',
        '    XFFFFFFFFFFFX    ',
        '    XFFFFFFFFFFFX    ',
        'XXXXXFFFFFFFFFFFXXXXX',
        'XIFFFFFFFFFFFFFFFFFCX',
        'XIFFFFFFFFFFFFFFFFFFX',
        'XXXXXXXXXXXXXXXXXXXXX',
    ],
    [
        'XXXXXXXXXXXXXXXXXXXXX',
        'XFCFXFFFFFFFFFFFFFFFD',
        'XFFFXFFFFFFFFFFFFFFFX',
        'XFFFXIFFFFFFFFFFFFFIX',
        'XFFFXFFXXXXXXXXXXXXXX',
        'XFFFXFFFFFFFFFFFFFFIX',
        'XFFFXFFFFFFFFFFFFFFFX',
        'XFFFXIFFFFFFFFFFFFFFX',
        'XFFFXXXXXXXXXXXXFFFFX',
        'XFFFXIFFFFFFFFFFFFFFX',
        'XFFFXFFFWFFFWFFFFFFFX',
        'XFFFFFFFWFFFWFFFFFFFX',
        'XFFFFFFFWFFFWFFFFFFFX',
        'XXXXXXXXXXXXXXXXXXXXX',
    ]
]
rooms_3 = [
    [
        'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
        'XIFFFFFFFFFFFFFFFFFFFFFFFFWFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFX',
        'XIFFFFWFFFFFFFFFFFFFFFFFFFWFFFFFFFFFFFFFFFFFFFFFFFFFFWFFFFFFFFFFFFFFFFFFFFX',
        'XFFFFFFFFFFFFFFFFFFFFFFFFFWFFFXXXXXXXXXXXXXXFFFFFFFFFFFFFFFFFFFWFFFFFFFFFFX',
        'XFFFFFFFFFFFFFFFFWFFFFFFFFWFFXFFFFFFFFFFFFFFXFFFFFFFFFFFFFFFFFFFFFFFFFFFFFX',
        'XFFFFFFFFFFFFFFFFFFFFFFFFFWFXFFFFFFFWFFFFFFFFXFFFFFFFFFFFFFFFFFFFFFFFFWFFFX',
        'XFFFFFWFFFFFFFFFFFWFFFFFFFWXFFFFFFFFFFFFFFFFFFXFFFFFFFFFWFFFFFFFFFFFFFFFFFX',
        'XFFFFFFFFFFFFFFFFFFFFFFFFFXFFFFFFFFFFFFFFFFFFFIXFFFFFFFFFFFFFFFFFFFFFFFFFFX',
        'XFFFFFFFFFFFFWFFFFFFFFFFFFFFFFFFFFFFCFFFFFFFFFIXFFFFFFFFFFFFFFFFWFFFFFFFFFD',
        'XFFFFFFFFFFFFFFFFFFFFFFFFFXFFFFFFFFFFFFFFFFFFFIXFFFFFFFFFFFFFFFFFFFFFFFFFFX',
        'XIFFFFFFFFFFFFFFFFWFFFFFFFWXFFFFFFFFFFFFFFFFFFXFFFFFFFFFWFFFFFFFFFFFFFFFFFX',
        'XFFFFFFFFWFFFFFFFFFFFFFFFFWFXFFFFFFFWFFFFFFFFXFFFFFFFFFFFFFFFFFFFFFFFFWFFFX',
        'XIFFFFFFFFFFFFFFFFFFFFFFFFFFFXFFFFFFFFFFFFFFXFFFFFWFFFFFFFFFFFFFFFFFFFFFFFX',
        'XIFFFFFFFFFFFFFFFWFFFFFFFFFFFFXXXXXXXXXXXXXXFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFX',
        'XIFFFFFFFFFFFFFFFFFFFFFFFFWFFFFFFFFFFFFFFFFFFFFFFFFFFFWFFFFFFFFFWFFFFFFFFFX',
        'XIFFFFFFFFFFWFFFFFFFFFFFFFWFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFX',
        'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    ],
    [
        'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
        'XIFFFFFFFFFFFFFFFFFFFFCFFFWFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFX',
        'XIFFFFWFFFFFFFFFFFFFFFFFFFWFFFFFFFFFFFFFFFFFFFFFFFFFFWFFFFFFFFFFFFFFFFFFFFX',
        'XFFFFFFFFFFFFFFFFFFFFFFFFFWFFFXXXXXXXXXXXXXXFFFFFFFFFFFFFFFFFFFWFFFFFFFFFFX',
        'XFFFFFFFFFFFFFFFFWFFFFFFFFWFFXFFFFFFFFFFFFFFXFFFFFFFFFFFFFFFFFFFFFFFFFFFFFX',
        'XFFFFFFFFFFFFFFFFFFFFFFFFFWFXFFFFFFFWFFFFFFFFXFFFFFFFFFFFFFFFFFFFFFFFFWFFFX',
        'XFFFFFWFFFFFFFFFFFWFFFFFFFWXFFFFFFFFFFFFFFFFFFXFFFFFFFFFWFFFFFFFFFFFFFFFFFX',
        'XFFFFFFFFFFFFFFFFFFFFFFFFFXFFFFFFFFFFFFFFFFFFFIXFFFFFFFFFFFFFFFFFFFFFFFFFFX',
        'XFFFFFFFFFFFFWFFFFFFFFFFFFFFFFFFFFFFWFFFFFFFFFIXFFFFFFFFFFFFFFFFWFFFFFFFFFD',
        'XFFFFFFFFFFFFFFFFFFFFFFFFFXFFFFFFFFFFFFFFFFFFFIXFFFFFFFFFFFFFFFFFFFFFFFFFFX',
        'XIFFFFFFFFFFFFFFFFWFFFFFFFWXFFFFFFFFFFFFFFFFFFXFFFFFFFFFWFFFFFFFFFFFFFFFFFX',
        'XFFFFFFFFWFFFFFFFFFFFFFFFFWFXFFFFFFFWFFFFFFFFXFFFFFFFFFFFFFFFFFFFFFFFFWFFFX',
        'XIFFFFFFFFFFFFFFFFFFFFFFFFFFFXFFFFFFFFFFFFFFXFFFFFWFFFFFFFFFFFFFFFFFFFFFFFX',
        'XIFFFFFFFFFFFFFFFWFFFFFFFFFFFFXXXXXXXXXXXXXXFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFX',
        'XIFFFFFFFFFFFFFFFFFFFFFFFFWFFFFFFFFFFFFFFFFFFFFFFFFFFFWFFFFFFFFFWFFFFFFFFFX',
        'XIFFFFFFFFFFWFFFFFFFFFFFFFWFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFX',
        'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    ],
    [
        'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
        'XXXXXXXWFFFFFFFFFFFXXXFFFFFFFFFFFFFXXXXXXXXXXXFFFFWXXXXFFFFFFFFFFFFFFFFFXXX',
        'XXXXWXXXXXXXXXXFXXFXXXFXXXXXXXXXXXFFFFFFFFFXXXFXXXXXXXXFXXXFXXXXXXXXXXXFXXX',
        'XXXXFXXXXXFFFFFFXXFFFFFFFFFWFFFFFFFXXXXXXXFXXXFXXXFFFFFFXXXXXXXXXXXXXXXFXXX',
        'XXXXFFFFFFFXXXXXXXXXXFXXXXXXXXXXXXXXFFCXXXFXXXFXXXFXXXXXXFFFFFFFFFFFXXXFFFD',
        'XXWXXXXXXXXXXXXFFFFFFFFFFXXFFFFFFXXXFXXXXXFXXXFFFFFXXXXXXFXXXXXXFXXFXXXFXXX',
        'XXFFFFFFFFFXXXXFXXXXXFXXFXXFXXXXFXXXFXXXXXFXXXFXXXFXXXXXXFXXXWFXFXXFXXXFXXX',
        'XXXXXXXXXXFFFFFFXWFFFFXXFFFFXXXXFFFFFXXXXFFFFFXXXFFFFFFFFFXXXXFFFXXFFFFFXXX',
        'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    ],
    [
        'XXXXXXXXXXXXX        XXXXXX          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
        'XFFFFFFFFFFFX       XFFWFFX         XFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFRFFFFXXX',
        'XFFFFXXXFFFFX    XXXFFFFFFXXXXXX   XFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFXXX',
        'XFFFRX XFFFFXXXXXFFFFFFFFFFFFFCX  XIFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFXXX',
        'XFFFFX XXXFFFFFFFFFIXXXXXXXXXXXX  XIFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFD',
        'XFFFRX    XXXXXXXXXXX             XIFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFXXX',
        'XFFFFXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXFFFFWFFFFFFFFFFFFFFFFFFWFFFFFFFFFFFFFXXX',
        'XFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFWFFFFFFFFFFFFXXX',
        'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    ],
    [
        'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
        'XFFFFIFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFXXX',
        'XFFFFIFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFXXX',
        'XFXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXFXXXXXXXXXXXXXXXXXXXFFFFFFFFFFFFFFFFFFFXXX',
        'XWX                             XFX                 XFFFFFFFFFFaFFFFFFFFXXX',
        'XXX                             XXX                 XFFFFFFFFFFFFFFFFFFFXXX',
        '                                                    XFFFFFFFFFFFFFFFFFFFXXX',
        'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXFFFFFFFFFFFFFFFFFFFXXX',
        'XFWFFFFFFFFWFFFFFFFFFFFFFFFFFFWFFFIFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFXXX',
        'XFFWFFFFFFFWFFFFFFFFFFFFFFFFFFWFFFFIFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFXXX',
        'XFFWFFFFFFFFFFFFFFFWFFFFFFFFFFFFFFFIFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFD',
        'XFWFFFFFFFFFFFFFFFFWFFFFFFFFFFFFFFIFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFXXX',
        'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXFFFFFFFFFFFFFFFFFFFXXX',
        '                                                    XFFFFFFFFFFFFFFFFFFFXXX',
        '                                                    XFFFFFFFFFFaFFFFFFFFXXX',
        'XXX                              XXX                XFFFFFFFFFFFFFFFFFFFXXX',
        'XCX                              XFX                XFFFFFFFFFFFFFFFFFFFXXX',
        'XFXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXFXXXXXXXXXXXXXXXXXXFFFFFFFFFFFFFFFFFFFXXX',
        'XIFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFXXX',
        'XIFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFXXX',
        'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    ],
    [
        'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
        'XFFFFIFFFFFFFFFFFFFFFFFFFFXIFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFXXX',
        'XFFFFIFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFXIFFFFFFFFFFFFFFFFFFFFFXXX',
        'XFFXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXFFXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXFFXXX',
        'XFFX                                XFFX                             XFFXXX',
        'XFFX                                XXXX                             XFFXXX',
        'XFFX                                                                 XFFXXX',
        'XFFXXXXXXXXXXXXXXXXXXXXXXXXXXX                XXXXXXXXXXXXXXXXXXXXXXXXFFXXX',
        'XFWFFFFFFFFFFFFFFFFFFFFFFFFFFX                XFFFFFFFFFFFFFFFFFFFFFFFFFXXX',
        'XFFFFFFFFFFFFFFFFaFFFFFFFFFFFX                XFFFFFFFFFaFFFFFFFFFFFFFFFXXX',
        'XFFFFFFFFFFFFFFFFFFFFFFFFFFFCX                XFFFFFFFFFFFFFFFFFFFFFFFFFFFD',
        'XFFFFFFFFFFFFFFFFFFFFFFFFFFFFX                XFFFFFFFFFFFFFFFFFFFFFFFFFXXX',
        'XFFXXXXXXXXXXXXXXXXXXXXXXXXXXX                XXXXXXXXXXXXXXXXXXXXXXXXFFXXX',
        'XFFX                                                                 XFFXXX',      #METER CREDITOS
        'XFFX                                                                 XFFXXX',
        'XFFX                                                                 XFFXXX',
        'XFFXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXFFXXX',
        'XIFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFWFFFWFFFFFFFFFFFFFFFWFFFFFFFFFFFFFFFFXXX',
        'XIFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFWFFFFFFFFFFFFFFFXXX',
        'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    ],
    [
        'XXXXXXXXXXXXXXXXXXXXX    XXXXXXXXXXXXXXXXXXXXX    XXXXXXXXXXXXXXXXXXXXX', 
        'XFFFFFFFFFFFFFFFFFFFX    XFFFFFFFFFFFFFFFFFFFX    XFFFFFFFFFFFFFFFFFFFX',
        'XFFFFFFFFFFFFFFFFFFFX    XFFFFFFFFFFFFFFFFFFFX    XFFFFFaFFFFFFFFFFFFFX',
        'XFFXFFFFFFFFFFFFFFFFXXXXXXFFFFFFFFaFFFFFFFFFFXXXXXXFFFFFFFFFFFFFFFFFFFX',
        'XCFXFFFFFFaFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFD',
        'XFFXFFFFFFFFFFFFFFFFXXXXXXFFFFFFFFFFFaFFFFFFFXXXXXXFFFFFFFFFFFFFFFFFFFX',
        'XFFFFFFFFFFFFFFFFFFFX    XFFFFFFFFFFFFFFFFFFFX    XFFFFFFFFFFFFFFaFFFFX',
        'XFFFFFFFFFFFFFFFFFFFX    XFFFFFFFFFFFFFFFFFFFX    XFFFFFFFFFFFFFFFFFFFX',
        'XXXXXXXXXXXXXXXXXXXXX    XXXXXXXXXXXXXXXXXXXXX    XXXXXXXXXXXXXXXXXXXXX', 
    ]
]
