tile_size = 32 #Tile size used as a base to construct the map

"""
    The following list works as a legend to indicate what letter represents wich object, player, npc, decoration or world generation tiles should be added

    'A' -> labcoat
    'a' -> table
    'B' -> glasses
    'b' -> left chair
    'i' -> elevator door
    'c' -> credits
    'C' -> letter
    'e' -> right chair
    'E' -> elevator
    'f' -> door carpet
    'F' -> floor
    'G' -> bottom right intersection
    'g' -> fruit1
    'h' -> fruit2
    'H' -> bottom left intersection
    'j' -> fruit3
    'J' -> top left intersection
    'K' -> top right intersection
    'k' -> Television
    'L' -> left wall
    'l' -> library light, when generating in the corridor
    'M' -> magic range enemy (Basic2)
    'm' -> library dark
    'N' -> nurse (NurseCharacter)
    'n' -> Bed01
    'Ñ' -> cauldron1
    'ñ' -> cauldron2
    'O' -> old man (ElderCharacter)
    'o' -> Bed02
    'P' -> player spawn.
    'p' -> plant
    'Q' -> crab enemy (Basic12)
    'q' -> Mate
    'R' -> right wall
    'R' -> rabbit enemy (Basic1)
    's' -> sofa left(grey)
    'S' -> sofa right(grey)
    'T' -> tracking enemy (Normal21)
    't' -> tracking enemy 2 (Normal22)
    'l' -> dragon enemy (Advanced2) moves to the left when generating in the room
    'r' -> dragon enemy (Advanced2) moves to the right when generating in the room
    'u' -> sofa left(brown)
    'U' -> sofa right(brown)
    'V' -> red lamp
    'v' -> blue lamp
    'W' -> worm enemy (Basic0)
    'w' -> bed table
    'X' -> bottom and top walls
    'x' -> cauldron3
    'Y' -> blue right sofa
    'y' -> blue left sofa
    'Z' -> purple right sofa
    'z' -> purple left sofa

Each level is made up of the basic_layout wich represents the corridor structure and a set
of rooms that can be generated for that layout
"""

#This is the basic_layout for the tutorial
tutorial_layout=[
    '            JXXXXXXXXK                                                 ',
    '            LFFFFFFFFR                                                 ',
    '            LFFFFFFFFR                                                 ',
    '            LFPFFFFFFR                                                 ',
    '            LFFFFFFFFR                                                 ',
    '            LFFFFFFFFH                                                 ',
    '            LFFFFFFFFX                                                 ',
    '            LFFFFFFFFJ                                                 ',
    '            LFFFFFFFFR                                                 ',
    '            LFFFFFFFFR                                                 ',
    '            LFFFFFFFFR                                                 ',
    '            LFFFFFFFFR                                                 ',
    '            HXXXXXXXXG                                                 ',
]

#This is the basic_layout for the first level were you spawn in your room
basic_layout = [
    '                                                                           ',
    '                                                                           ',
    '                                                                           ',
    '                                                                           ',
    '                                                                           ',
    '                                                                           ',
    '                                                                           ',
    '                                                                           ',
    '                                                                           ',
    '                JXXXXXXXXK                                                 ',
    '                LmFFkFFFFR                                                 ',
    '                LFFFFFFFFR                                                 ',
    '                LFPFFFFFFR                                                 ',
    '                LFFFFFFFFRJXXXXXXXXK                                       ',
    '                LqFFFFFFFHGFFFNFFFFH                                       ',
    '                LFFbaeFFFFFfFFFFFFfD                                       ',
    '                LFFFFFFFFJKFFFFFFFFJ                                       ',
    '                LFFFFFFFFRLFFFFFFFFR                                       ',
    '                LFFwFFFFFRLsFFFFFFSL                                       ',
    '                LFnFFFFoFRLFFFFFOFFR                                       ',
    '                LFFFFFFFFRLgFFFFFFhR                                       ',
    '                HXXXXXXXXGLuFFFFFFUR                                       ',
    '                          LFFFFFFFFR                                       ',
    '                          LÑFFFFFFñR                                       ',
    '                          LFFFFFFFFR                                       ',
    '                          LFFFFFFFFR                                       ',
    '                          LFNFFFFFFR                                       ',
    '                          LFFFFFFFFR                                       ',
    '                          LsFFFFFFSR                                       ',
    '                          LFFFFFFFFR                                       ',
    '                          LjFFFFFFgR                                       ',
    '                          LuFOFFFFUR                                       ',
    '                          LFFFFFFFFR                                       ',
    '                          GñFFFFFFÑH                                       ',
    '                          DfFFFFFFfD                                       ',
    '                          KFFFFFFFFJ                                       ',
    '                          LFFFFFFFFR                                       ',
    '                          LsFFFFNFSR                                       ',
    '                          LFFFFFFFFR                                       ',
    '                          LjFFFFFFhR                                       ',
    '                          LuFFFFFFUR                                       ',
    '                          LFFFFFFFFR                                       ',
    '                          LñFFFFFFÑR                                       ',
    '                          LFFFFFFFFR                                       ',
    '                          LFFFFFFFFR                                       ',
    '                          LFNFFFNFFR                                       ',
    '                          LsFFFFFFSR                                       ',
    '                          LFFFFFFFFR                                       ',
    '                          LjFFFFFFgR                                       ',
    '                          LuFFFFFFUR                                       ',
    '                          LFFFFFFFFR                                       ',
    '                          LÑFFFFFFñR                                       ',
    '                          LFFFFFFFFH                                       ',
    '                          LsFFOFFFfD                                       ',
    '                          LFFFFFFFFJ                                       ',
    '                          LFFFFFFFFR                                       ',
    '                          GFFFFFFFFR                                       ',
    '                          DfFFFFFFFR                                       ',
    '                          KFFFFFFFFR                                       ',
    '                          LFFFFFFFFR                                       ',
    '                          LFFFFFFFFR                                       ',
    '                          LsFFFFFFSR                                       ',
    '                          LFFFFFNFFR                                       ',
    '                          LuFFFFFFUR                                       ',
    '                          LhFFFFFFgR                                       ',
    '                          LFFFFFFFFR                                       ',
    '                          LñFFFFFFÑR                                       ',
    '                          LFFFFFFFFR                                       ',
    '                          LFFFFFFNFR                                       ',
    '                          LsFFFFFFSR                                       ',
    '                          LFFFFFFFFR                                       ',
    '                          LjFFFFFFÑH                                       ',
    '                          LuFFFFFFfD                                       ',
    '                          LFFFFFFFFJ                                       ',
    '                          LÑFFFFFFFR                                       ',
    '                          GFFFFFFFFR                                       ',
    '                          DfFFFFFFFR                                       ',
    '                          KFFFFFFFFR                                       ',
    '                          LFFFFFFFFR                                       ',
    '                          LFFFFFFFFR                                       ',
    '                          LFFFFFFFFR                                       ',
    '                          LFFFFFFFFR                                       ',
    '                          LFFFFFFFFR                                       ',
    '                          LFFFFFFFFR                                       ',
    '                          LFFFFFFFFE                                       ',
    '                          LFFFFFFFFR                                       ',
    '                          LFFFFFFFFR                                       ',
    '                          HXXXXXXXXG                                       ',
    '                                                                           ',
    '                                                                           ',
    '                                                                           ',
    '                                                                           ',
    '                                                                           ',
    '                                                                           ',
    '                                                                           ',
    '                                                                           ',
    '                                                                           ',
    '                                                                           ',
    '                                                                           ',
]

#This is the basic_layout for the second level
basic_layout_2 = [
    '                                                                                                                                                                    ',
    '                                                                                                                                                                    ',
    '                                                                                                                                                                    ',
    '                                                                                                                                                                    ',
    '                                                                                                                                                                    ',
    '                                                                                                                                                                    ',
    '                                                                                                                                                                    ',
    '                                                                                                                                                                    ',
    '                                                                                                                                                                    ',
    '                                                                                                                                                                    ',
    '                                                                                                                                                                    ',
    '                                                                                                                                                                    ',
    '                                                                                                                                                                    ',
    '                                                                                                                                                                    ',
    '                                                                                                                                                                    ',
    '                                                                                                                                                                    ',
    '                                                                                                                                                                    ',
    '                                                                                                                                                                    ',
    '                                                                                                                                                                    ',
    '                                                                                                                                                                    ',
    '                                                                                                                                                                    ',
    '                                                                                                                                                                    ',
    '                                                                                                                                                                    ',
    '                                                                                                                                                                    ',
    '                                                                                                                                                                    ',
    '                                                                             JXXXXXXXXK                                                                             ',
    '                                                                             LFFFiFFFFR                                                                             ',
    '                                                                             DfPFFFFFfD                                                                             ',
    '                                                                             LpFFFFFFpR                                                                             ',
    '                                                                             LvFFFFFNvR                                                                             ',
    '                                                                             LyFFFFFFYR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LjFFFFFFhR                                                                             ',
    '                                                                             LzFFFFFFZR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LgFFFFFFgR                                                                             ',
    '                                                                             LyFFFFFFYR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFOFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LOFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LVNFFFFFVR                                                                             ',
    '                                                                             LyFFFFFFYR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LgFFFFFFhR                                                                             ',
    '                                                                             LzFFFFFFZR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LgFFFFFFjR                                                                             ',
    '                                                                             LyFFFFFFYR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LpFFFFFFpR                                                                             ',
    '                                                                             LFFFFNFFFR                                                                             ',
    '                                                                             DfFFFFFFfD                                                                             ',
    '                                                                             LpFFFFFFpR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LVFFFFFFvR                                                                             ',
    '                                                                             LzFFFFFFZR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LjFFFFFFhR                                                                             ',
    '                                                                             LyFFFFFFYR                                                                             ',
    '                                                                             LFOFFFFFFR                                                                             ',
    '                                                                             LgFFFFFFhR                                                                             ',
    '                                                                             LzFFFFFFZR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LVFFFFFFvR                                                                             ',
    '                                                                             LzFFFFFFZR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LjFOFFFFhR                                                                             ',
    '                                                                             LyFFFFFFYR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LgFFFFFOgR                                                                             ',
    '                                                                             LzFFFFFFZR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LpFFFFFFpR                                                                             ',
    '                                                                             LFFFFFNFFR                                                                             ',
    '                                                                             DfFFFFFFfD                                                                             ',
    '                                                                             LpFFFFFFpR                                                                             ',
    '                                                                             LFNFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LvFFFFFFvR                                                                             ',
    '                                                                             LyFFFFFFYR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LjFFFFFFhR                                                                             ',
    '                                                                             LzFFFFFFZR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LjFFFFFFgR                                                                             ',
    '                                                                             LyFFFFFFYR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFNFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LvFFFFFFVR                                                                             ',
    '                                                                             LzFFFFFFZR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LjFFFFFFgR                                                                             ',
    '                                                                             LyFFFFFFYR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LhFFFFFFhR                                                                             ',
    '                                                                             LzFFFFFFZR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LpFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             DfFFFNFFFR                                                                             ',
    '                                                                             LpFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFpR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFfE                                                                             ',
    '                                                                             LFFFFFFFpR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             HXXXXXXXXG                                                                             ',
    '                                                                                                                                                                    ',
    '                                                                                                                                                                    ',
    '                                                                                                                                                                    ',
    '                                                                                                                                                                    ',
    '                                                                                                                                                                    ',
    '                                                                                                                                                                    ',
    '                                                                                                                                                                    ',
    '                                                                                                                                                                    ',
    '                                                                                                                                                                    ',
    '                                                                                                                                                                    ',
    '                                                                                                                                                                    ',
]

#This is the basic_layout for the second level
basic_layout_3 = [
    '                                                                                                                                                                    ',
    '                                                                                                                                                                    ',
    '                                                                                                                                                                    ',
    '                                                                                                                                                                    ',
    '                                                                                                                                                                    ',
    '                                                                                                                                                                    ',
    '                                                                                                                                                                    ',
    '                                                                                                                                                                    ',
    '                                                                                                                                                                    ',
    '                                                                                                                                                                    ',
    '                                                                                                                                                                    ',
    '                                                                                                                                                                    ',
    '                                                                                                                                                                    ',
    '                                                                             JXXXXXXXXK                                                                             ',
    '                                                                             LFFFiFFFpR                                                                             ',
    '                                                                             DfPFFFFFFR                                                                             ',
    '                                                                             LpFFFFFFfD                                                                             ',
    '                                                                             LFFFOFFFpR                                                                             ',
    '                                                                             LyFFFFFFYR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LgFFFFFFÑR                                                                             ',
    '                                                                             LsFFFFFFSR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LyFFFFFFYR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LÑFFFFFFñR                                                                             ',
    '                                                                             LsFOFFFFSR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LsFFFFFFpR                                                                             ',
    '                                                                             LFFFFFFNFR                                                                             ',
    '                                                                             LñFFFFFFfD                                                                             ',
    '                                                                             LFFFFFFFpR                                                                             ',
    '                                                                             LpFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             DfFFNFFFSR                                                                             ',
    '                                                                             LpFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LsFFFFFFSR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LhFFFFFFjR                                                                             ',
    '                                                                             LyFFFFFFYR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LgFFFFFFhR                                                                             ',
    '                                                                             LsFFFFFFSR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LyFFFFFFpR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LñFFFFFFfD                                                                             ',
    '                                                                             LFFFFFFOpR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LsFFFFFFSR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LgFFFFFFhR                                                                             ',
    '                                                                             LsFFFFFFSR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LNFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LyFFFFFFSR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LjFFFFFFñR                                                                             ',
    '                                                                             LyFFFFFFpR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LjFFFFFFfD                                                                             ',
    '                                                                             LFFFFFFFpR                                                                             ',
    '                                                                             LpFFFFFFFR                                                                             ',
    '                                                                             LFFFFNFFFR                                                                             ',
    '                                                                             DfFFFFFFFR                                                                             ',
    '                                                                             LpFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFYR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             LsFFFFFFFR                                                                             ',
    '                                                                             LFFFFFFFpR                                                                             ',
    '                                                                             LhFFFFFFFR                                                                             ',
    '                                                                             LyFFFFFFfE                                                                             ',
    '                                                                             LFFFFFFFpR                                                                             ',
    '                                                                             LFFFFFFFFR                                                                             ',
    '                                                                             HXXXXXXXXG                                                                             ',
    '                                                                                                                                                                    ',
    '                                                                                                                                                                    ',
    '                                                                                                                                                                    ',
    '                                                                                                                                                                    ',
    '                                                                                                                                                                    ',
    '                                                                                                                                                                    ',
    '                                                                                                                                                                    ',
    '                                                                                                                                                                    ',
    '                                                                                                                                                                    ',
    '                                                                                                                                                                    ',
    '                                                                                                                                                                    ',
]

#Set of rooms for level 1
rooms_1 = [
    [
        'XXXXXXXXXXXX  XXXXXX',
        'XAFBFFFFFFFXXXXFFFFX',
        'XFFFFWFFFFFFFFFFFFFD',
        'XFCFFFFFFFFFWFFFFFFX',
        'XFFFWFFFFFFFFFFFFFFX',
        'XFFFFFFFFFFXXXXFFFFX',
        'XXXXXXXXXXXX  XXXXXX',
    ],
    [
        'XXXXXXXXXXXXXXXXXXXX',
        'XFAFFFFFFFFFFFFFFFFX',
        'XFFFFFFFFFFFFFFFFFFX',
        'XFFFFFFFWWFFFFFFFFFX',
        'XFFFFFFFFFFFFFQFFFFX',
        'XFFFFFFFFFFFFFFFFFFX',
        'XXXXXXXXFFXXXXXXXXXX',
        '       XFFX         ',
        'XXXXXXXXFFXXXXXXXXXX',
        'XFFFFFFFFFFFFFFFFFFX',
        'XFCFFFFFFFFFFFFFFFFD',
        'XFFFFFFFFFFFFFFQFFFX',
        'XFFFFFFFFFFFFFFFFFFX',
        'XXXXXXXXXFFXXXXXXXXX',
        '        XFFX        ',
        'XXXXXXXXXFFXXXXXXXXX',
        'XFFFFFFFFFFFFFFFFFFX',
        'XFWFFFFFFFFFFFFFFFFX',
        'XFFFFFFFFFFFFFFQFFFX',
        'XBFFFWFFFFFFFFFFFFFX',
        'XXXXXXXXXXXXXXXXXXXX',
    ],
    [
        'XXXXXXXXXXXX',
        'XCFFFFFFFFBX',
        'XFFFFFFFFFFX',
        'XFFFFFFFRFFX',
        'XFFFFWFFFFFX',
        'XFFFFFFFFFFD',
        'XFFFFFFFFFFX',
        'XFFFFWFFFFFX',
        'XFFFQFFFFFFX',
        'XAFFFFFFFFFX',
        'XXXXXXXXXXXX',
    ],
    [
        'XXXXXXXXXXXXXXXXXXXXX',
        'XFCFFFFFFFFFFFFWFFFBX',
        'XFFFFFQFFFFFFFFFFFFFD',
        'XAFFFFFFFFWFFFFFFFFFX',
        'XXXXXXXXXXXXXXXXXXXXX',
    ],
    [
        'XXXXXXXXXXXXXXXXXXXXX',
        'XFCFFWFFFFFFFFWFFFFBX',
        'XFFFFFFFFFRFFFFFFFFFX',
        'XFFFFFFFWFFFFFFFFFFFX',
        'XFFFFFFFFFFFFFFFFFFFD',
        'XFFFFFWFFFFFFWFFFFFFX',
        'XFFFFFFFFFFRFFFFFFFFX',
        'XAFFFFFFFFFFFFFFFFFFX',
        'XXXXXXXXXXXXXXXXXXXXX',
    ],
    [
        'XXXXXXXXX   XXXXXXXXX',
        'XFCFFFFBX   XFFFFFFFX',
        'XFFFFFFFXXXXXFFFFWFFX',
        'XFFFFFFFRFFFFFFFFFFFX',
        'XFFFFFFFFFFFFFFFFFFFX',
        'XFFFFFQFFFFFFFFFFFFFD',
        'XFFFFFFFFFFFFFRFFFFFX',
        'XFFFFFFFFFWFFFFFFWFFX',
        'XFFFFFFFXXXXXFFFFFFFX',
        'XAFFFFFFX   XFFFFFFFX',
        'XXXXXXXXX   XXXXXXXXX',
    ],
    [
        'XXXXXXXX                ',
        'XBFFFFFX                ',
        'XFFFWFFX                ',
        'XFFFFFFXXXXXXXXXXXXXXXXX',
        'XCFFFFFFFFFWFFFFFFFFFFFX',
        'XFFFFFFFFFFFFFFFFFFFFFFX',
        'XFFFFFFFFFRFFFFFFFFFFFFD',
        'XFFFFFFFFFFFFFFFFFFFFFFX',
        'XFFFFFFFFFFFFFFFFWFFFFFX',
        'XFFFFFFXXXXXXXXXXXXXXXXX',
        'XFFFFFFX                ',
        'XFFFFFAX                ',
        'XXXXXXXX                ',
    ],
    [
        'XXXXXXXXXXXXXXXXXX ',
        'XFFFFFFFWFFFFFFFAX ',
        'XFFFFFFFFFFQFFFFFX ',
        'XFFFFFFFFFFFFFFFFX ',
        'XFFFFXXXXXXXXXXXXX ',
        'XFFFFXXXXXXXXXXXXXX',
        'XCFFFFFFFFFFFFFFFFX',
        'XFFFFFFFQFFFFFFFFFD',
        'XFFFFFFFFFFFFFFFFFX',
        'XFFFFXXXXXXXXXXXXXX',
        'XFFFFXXXXXXXXXXXXX ',
        'XFFFFFFFFFFFFFFFFX ',
        'XFFFFFFFFFQFFFFFFX ',
        'XFFFFFFFFFFFFFFFFX ',
        'XFFFFFFFWFFFFFFFBX ',
        'XXXXXXXXXXXXXXXXXX ',
    ],
    [
        'XXXXXXXXXXXXXXXXXXXXX',
        'XFFFFFFFFFFFFFFFFFFFX',
        'XFFFFFFFFFFFFFFFFFFFD',
        'XFQFFFFFFFFFFFFFFFFFX',
        'XFFFFFFFFFFFFFFFFFFFX',
        'XFFFXXXXXXXXXXXXXXXXX',
        'XFFFWFFFFFFFFFFFFFFFX',
        'XFFFFFFFFFFFFFFFFFFFX',
        'XFFFFFFFFFFFFFFFFQFFX',
        'XFFFFFFWFFFFFFFFFFFFX',
        'XXXXXXXXXXXXXXXXFFFFX',
        'XCFFFWFFFFFFFFFFFFFFX',
        'XFFFFFFFFFFFFWFFFFFFX',
        'XAFFFFFFFWFFFFFFFFFFX',
        'XXXXXXXXXXXXXXXXXXXXX',
    ],
]

#Set of rooms for level 2
rooms_2 = [
    [
        'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
        'XFFFFCFFFFFXFFFFFFFFFFFFFFFFFFFFFXFFFFFFFFFXFFFFFFFFFD',
        'XFFFFFFFFFFXrFFFFFFFFFFFFFFFFFFFFXFFFFFFFFFXFFFFFFFFFX',
        'XFFFFFFFFFFXFFFFFFFFFXFFFFFFFFFFFXFFFFFFFFFXFFFFFFFFFX',
        'XFFFFFFFFFFXFFFFFFFFFXFFFFFFFFFFFXFFFFFFFFFFFFFFFFFFFX',
        'XFFFFFFFFFFXFFFFFFFFFXFFFFFFFFFFFXFFFFFFFFFXFFFFFFFFFX',
        'XrFFFFFFFFFFFFFFFFFFFXrFFFFFFFFFFFFFFFFFFFFXFFFFFFFFFX',
        'XrFFFFFFFFFFFFFFFFFFFXrFFFFFFFFFFFFFFFFFFFFXFFFFFFFFFX',
        'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    ],
    [
        'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
        'XFFFFFFFFXFFFFFFFXFFFFFFFFFFFFFFFFFFFFFFFXFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFX',
        'XFFFCFFFFFFFFFFFRrFFFFFFFFFFFFFFFFFFRFFFFFrFFFFFFFRFFFFFFFFFFFFFFFFFFFFFFFD',
        'XFFFFFFFFXrFFFFFFFFFFFFFFFFFFXrFFFFFFFFFFFFFFFFFFFFFFXrFFFFFFFFFFFFFFFFFFFX',
        'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    ],
    [
        'XXXXXXXXXXXX',
        'XFFFFFCFFFFX',
        'XFFFFFFFFFFX',
        'XrFFFFFFFFFX',
        'XFFFFFFFFFlX',
        'XrFFFFFFFFFX',
        'XFFFFFFFFFlX',
        'XrFFFFFFFFFX',
        'XFFFFFFFFFlX',
        'XrFFFFFFFFFX',
        'XFFFFFFFFFlX',
        'XrFFFFFFFFFX',
        'XFFFFFFFFFlX',
        'XrFFFFFFFFFX',
        'XFFFFFFFFFlX',
        'XrFFFFFFFFFX',
        'XFFFFFFFFFlX',
        'XrFFFFFFFFFX',
        'XFFFFFFFFFlX',
        'XrFFFFFFFFFX',
        'XFFFFFFFFFlX',
        'XrFFFFFFFFFX',
        'XFFFFFFFFFlX',
        'XrFFFFFFFFFX',
        'XFFFFFFFFFFD',
        'XXXXXXXXXXXX',
    ],
    [
        'XXXXXXXXXXXXXXXXXXXXX', 
        'XFFFFFFFFFFFFFFFFFFFX',
        'XFFFFFFFFFFFFFFFFFFFX',
        'XFFFFFFFFFaFFFFFFFFFX',
        'XFFXFFFFFFFFFFFFFFFFX',
        'XCFXFFFFFFFFFFFFFFFFD',
        'XFFXFFFFFFFFFFFFFFFFX',
        'XFFFFFFFFFaFFFFFFFFFX',
        'XFFFFFFFFFFFFFFFFFFFX',
        'XFFFFFFFFFFFFFFFFFFFX',
        'XXXXXXXXXXXXXXXXXXXXX',
    ],
    [
        'XXXXXXXXXXXXXXXXXXXXX',
        'XFFFFFFFFFFFFFFFFFFFX',
        'XFFFFFFFFFFFFFFFFFFFX',
        'XCFFFFFFFFFFFFFFFFFFX',
        'XFFFFFFFFFFFFFFFFFFFD',
        'XFFFFFFFFFFFFFFFFFFFX',
        'XFFFFFFFFFFFFFFFFFFFX',
        'XFFFFFFFFFFFFFFFFFFFX',
        'XXXXXXXXXXXXXXXXXXXXX',
    ],
    [
        '    XXXXXXXXXXXXX    ',
        '    XFFFFFWFFFFFX    ',
        '    XFFFFFFFFFFFX    ',
        'XXXXXFFWFFFFFWFFXXXXX',
        'XFFFFFFFFFFFFFFFFFFFD',
        'XFFWFFFFFFFFFFFFFWFFX',
        'XFFFFFFFFFaFFFFFFFFFX',
        'XFFWFFFFFFFFFFFFFWFFX',
        'XFFFFFWFFFFFFFWFFFFFX',
        'XXXXXFFFFFFFFFFFXXXXX',
        '    XFFFFFFFFFFFX    ',
        '    XFFFFFCFFFFFX    ',
        '    XXXXXXXXXXXXX    ',
    ],
    [
        '    XXXXXXXXXXXXX    ',
        '    XFFFFFFFFFFFX    ',
        '    XFFFFFFFFFFFX    ',
        '    XFFFFFTFFFFFX    ', 
        '    XFFFFFFFFFFFX    ',
        '    XFFFFFFFFFFFX    ',
        '    XFFFFFFFFFFFX    ',
        'XXXXXFFFFFFFFFFFXXXXX',
        'XFFFFFFFFFFFFFFFFFFFD',
        'XFFFFFFFFFFFFFFFFFFFX',
        'XFFFFFFFFaFFFFFFFFFFX',
        'XFFFFFFFFFFFFFFFFFFFX',
        'XFFFFFFFFFFFFFFFFFFFX',
        'XXXXXFFFFFFFFFFFXXXXX',
        '    XFFFFFFFFFFFX    ',
        '    XFFFFFFFFFFFX    ',
        '    XFFFFFFFFFFFX    ',
        'XXXXXFFFFFFFFFFFXXXXX',
        'XrFFFFFFFFFFFFFFFFFCX',
        'XrFFFFFFFFFFFFFFFFFFX',
        'XXXXXXXXXXXXXXXXXXXXX',
    ],
    [
        'XXXXXXXXXXXXXXXXXXXXX',
        'XFCFXFFFFFFFFFFFFFFFD',
        'XFFFXFFFFFFFFFFFFFFFX',
        'XFFFXrFFFFFFFFFFFFFlX',
        'XFFFXFFXXXXXXXXXXXXXX',
        'XFFFXFFFFFFFFFFFFFFFX',
        'XFFFXFFFFFFFFFFFFFFlX',
        'XFFFXrFFFFFFFFFFFFFFX',
        'XFFFXXXXXXXXXXXXFFFFX',
        'XFFFXFFFFFFFFFFFFFFFX',
        'XFFFXrFFFFFFFFFFFFFFX',
        'XFFFFFFFWFFFWFFFFFFFX',
        'XFFFFFFFWFFFWFFFFFFFX',
        'XXXXXXXXXXXXXXXXXXXXX',
    ]
]

#Set of rooms for level 3
rooms_3 = [
    [
        'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
        'XFFFFFFFFFFFFFFFFFFFFFFFFFWFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFX',
        'XrFFFFWFFFFFFFFFFFFFFFFFFFWFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFX',
        'XFFFFFFFFFFFFFFFFFFFFFFFFFWFFFXXXXXXXXXXXXXXFFFFFFFFFFFFFFFFFFFWFFFFFFFFFFX',
        'XFFFFFFFFFFFFFFFFWFFFFFFFFWFFXFFFFFFFFFFFFFFXFFFFFFFFFFFFFFFFFFFFFFFFFFFFFX',
        'XFFFFFFFFFFFFFFFFFFFFFFFFFWFXFFFFFFFWFFFFFFFFXFFFFFFFFFFFFFFFFFFFFFFFFWFFFX',
        'XFFFFFWFFFFFFFFFFFFFFFFFFFWXFFFFFFFFFFFFFFFFFFXFFFFFFFFFFFFFFFFFFFFFFFFFFFX',
        'XFFFFFFFFFFFFFFFFFFFFFFFFFXFFFFFFFFFFFFFFFFFFFFXFFFFFFFFFFFFFFFFFFFFFFFFFFX',
        'XFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCFFFFFFFFFlXFFFFFFFFFFFFFFFFWFFFFFFFFFD',
        'XFFFFFFFFFFFFFFFFFFFFFFFFFXFFFFFFFFFFFFFFFFFFFlXFFFFFFFFFFFFFFFFFFFFFFFFFFX',
        'XrFFFFFFFFFFFFFFFFWFFFFFFFWXFFFFFFFFFFFFFFFFFFXFFFFFFFFFFFFFFFFFFFFFFFFFFFX',
        'XFFFFFFFFFFFFFFFFFFFFFFFFFWFXFFFFFFFWFFFFFFFFXFFFFFFFFFFFFFFFFFFFFFFFFWFFFX',
        'XrFFFFFFFFFFFFFFFFFFFFFFFFFFFXFFFFFFFFFFFFFFXFFFFFFFFFFFFFFFFFFFFFFFFFFFFFX',
        'XrFFFFFFFFFFFFFFFWFFFFFFFFFFFFXXXXXXXXXXXXXXFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFX',
        'XrFFFFFFFFFFFFFFFFFFFFFFFFWFFFFFFFFFFFFFFFFFFFFFFFFFFFWFFFFFFFFFWFFFFFFFFFX',
        'XrFFFFFFFFFFWFFFFFFFFFFFFFWFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFX',
        'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    ],
    [
        'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
        'XFFFFFFFFFFFFFFFFFFFFFCFFFWFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFX',
        'XrFFFFFFFFFFFFFFFFFFFFFFFFWFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFX',
        'XFFFFFFFFFFFFFFFFFFFFFFFFFWFFFXXXXXXXXXXXXXXFFFFFFFFFFFFFFFFFFFWFFFFFFFFFFX',
        'XFFFFFFFFFFFFFFFFWFFFFFFFFWFFXFFFFFFFFFFFFFFXFFFFFFFFFFFFFFFFFFFFFFFFFFFFFX',
        'XFFFFFFFFFFFFFFFFFFFFFFFFFWFXFFFFFFFWFFFFFFFFXFFFFFFFFFFFFFFFFFFFFFFFFWFFFX',
        'XFFFFFFFFFFFFFFFFFWFFFFFFFWXFFFFFFFFFFFFFFFFFFXFFFFFFFFFFFFFFFFFFFFFFFFFFFX',
        'XFFFFFFFFFFFFFFFFFFFFFFFFFXFFFFFFFFFFFFFFFFFFFFXFFFFFFFFFFFFFFFFFFFFFFFFFFX',
        'XFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFWFFFFFFFFFlXFFFFFFFFFFFFFFFFWFFFFFFFFFD',
        'XFFFFFFFFFFFFFFFFFFFFFFFFFXFFFFFFFFFFFFFFFFFFFlXFFFFFFFFFFFFFFFFFFFFFFFFFFX',
        'XrFFFFFFFFFFFFFFFFWFFFFFFFFXFFFFFFFFFFFFFFFFFFXFFFFFFFFFWFFFFFFFFFFFFFFFFFX',
        'XFFFFFFFFFFFFFFFFFFFFFFFFFFFXFFFFFFFWFFFFFFFFXFFFFFFFFFFFFFFFFFFFFFFFFWFFFX',
        'XrFFFFFFFFFFFFFFFFFFFFFFFFFFFXFFFFFFFFFFFFFFXFFFFFFFFFFFFFFFFFFFFFFFFFFFFFX',
        'XrFFFFFFFFFFFFFFFFFFFFFFFFFFFFXXXXXXXXXXXXXXFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFX',
        'XrFFFFFFFFFFFFFFFFFFFFFFFFWFFFFFFFFFFFFFFFFFFFFFFFFFFFWFFFFFFFFFWFFFFFFFFFX',
        'XrFFFFFFFFFFWFFFFFFFFFFFFFWFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFX',
        'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    ],
    [
        'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
        'XXXXXXXWFFFFFFFFFFFXXXFFFFFFFFFFFFFXXXXXXXXXXXFFFFWXXXXFFFFFFFFFFFFFFFFFXXX',
        'XXXXWXXXXXXXXXXFXXFXXXFXXXXXXXXXXXFFFFFFFFFXXXFXXXXXXXXFXXXFXXXXXXXXXXXFXXX',
        'XXXXFXXXXXFFFFFFXXFFFFFXXXXWFFFFFFFXXXXXXXFXXXFXXXFFFFFFXXXXXXXXXXXXXXXFXXX',
        'XXXXFXXXXXFXXXXXXXXXXFXXXXXWFFFFFFFXXXXXXXFXXXFXXXFFFFFFXXXXXXXXXXXXXXXFXXX',
        'XXXXFXXXXXFXXXXXXXXXXFXXXXXWFFFFFFFXXXXXXXFXXXFXXXFFFFFFXXXXXXXXXXXXXXXFXXX',
        'XXXXFXXXXXFXXXXXXXXXXFXXXXXWFFFFFFFXXXXXXXFXXXFXXXFFFFFFXXXXXXXXXXXXXXXFXXX',
        'XXXXFFFFFFFXXXXXXXXXXFXXXXXXXXXXXXXXFFCXXXFXXXFXXXFXXXXXXFFFFFFFFFFFXXXFFFD',
        'XXWXXXXXXXXXXXXFFFFFFFFFFXXFFFFFFXXXFXXXXXFXXXFFFFFXXXXXXFXXXXXXFXXFXXXFXXX',
        'XXFFFFFFFFFXXXXFXXXXXFXXFXXFXXXXFXXXFXXXXXFXXXFXXXFXXXXXXFXXXWFXFXXFXXXFXXX',
        'XXXXXXXXXXFFFFFFXWFFFFXXFFFFXXXXFFFFFXXXXFFFFFFXXFFFFFFFFFXXXXFFFXXFFFFFXXX',
        'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    ],
    [
        'XXXXXXXXXXXXX        XXXXXX          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
        'XFFFFFFFFFFFX       XFFWFFX         XFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFRFFFFXXX',
        'XFFFFXXXFFFFX    XXXFFFFFFXXXXXX   XFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFXXX',
        'XFFFRX XFFFFXXXXXFFFFFFFFFFFFFCX  XFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFXXX',
        'XFFFFX XXXFFFFFFFFFlXXXXXXXXXXXX  XrFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFD',
        'XFFFRX    XXXXXXXXXXX             XrFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFXXX',
        'XFFFFXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXFFFFWFFFFFFFFFFFFFFFFFFWFFFFFFFFFFFFFXXX',
        'XFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFWFFFFFFFFFFFFXXX',
        'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    ],
    [
        'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
        'XFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFXXX',
        'XFFFFrFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFXXX',
        'XFXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXFXXXXXXXXXXXXXXXXXXXFFFFFFFFFFFFFFFFFFFXXX',
        'XWX                             XFX                 XFFFFFFFFFFaFFFFFFFFXXX',
        'XXX                             XXX                 XFFFFFFFFFFFFFFFFFFFXXX',
        '                                                    XFFFFFFFFFFFFFFFFFFFXXX',
        'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXFFFFFFFFFFFFFFFFFFFXXX',
        'XFWFFFFFFFFWFFFFFFFFFFFFFFFFFFWFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFXXX',
        'XFFWFFFFFFFWFFFFFFFFFFFFFFFFFFWFFFFrFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFXXX',
        'XFFWFFFFFFFFFFFFFFFWFFFFFFFFFFFFFFFlFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFD',
        'XFWFFFFFFFFFFFFFFFFWFFFFFFFFFFFFFFlFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFXXX',
        'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXFFFFFFFFFFFFFFFFFFFXXX',
        '                                                    XFFFFFFFFFFFFFFFFFFFXXX',
        '                                                    XFFFFFFFFFFaFFFFFFFFXXX',
        'XXX                              XXX                XFFFFFFFFFFFFFFFFFFFXXX',
        'XCX                              XFX                XFFFFFFFFFFFFFFFFFFFXXX',
        'XFXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXFXXXXXXXXXXXXXXXXXXFFFFFFFFFFFFFFFFFFFXXX',
        'XFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFXXX',
        'XlFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFXXX',
        'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    ],
    [
        'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
        'XFFFFFFFFFFFFFFFFFFFFFFFFFXFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFXXX',
        'XFFFFrFFFFFFFFFFFFFFFFFFFFFrFFFFFFFFFFFFFFFFFFFFFXrFFFFFFFFFFFFFFFFFFFFFXXX',
        'XFFXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXFFXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXFFXXX',
        'XFFX                                XFFX                             XFFXXX',
        'XFFX                                XXXX                             XFFXXX',
        'XFFX                                                                 XFFXXX',
        'XFFXXXXXXXXXXXXXXXXXXXXXXXXXXX                XXXXXXXXXXXXXXXXXXXXXXXXFFXXX',
        'XFWFFFFFFFFFFFFFFFFFFFFFFFFFFX                XFFFFFFFFFFFFFFFFFFFFFFFFFXXX',
        'XFFFFFFFFFFFFFFFFaFFFFFFFFFFFX                XFFFFFFFFFaFFFFFFFFFFFFFFFXXX',
        'XFFFFFFFFFFFFFFFFFFFFFFFFFFFCX                XFFFFFFFFFFFFFFFFFFFFFFFFFFFD',
        'XFFFFFFFFFFFFFFFFFFFFFFFFFFFFX                XFFFFFFFFFFFFFFFFFFFFFFFFFXXX',
        'XFFXXXXXXXXXXXXXXXXXXXXXXXXXXX                XXXXXXXXXXXXXXXXXXXXXXXXFFXXX',
        'XFFX                                                                 XFFXXX',
        'XFFX                                                                 XFFXXX',
        'XFFX                                                                 XFFXXX',
        'XFFXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXFFXXX',
        'XFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFWFFFWFFFFFFFFFFFFFFFWFFFFFFFFFFFFFFFFXXX',
        'XrFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFWFFFFFFFFFFFFFFFXXX',
        'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    ],
    [
        'XXXXXXXXXXXXXXXXXXXXX    XXXXXXXXXXXXXXXXXXXXX    XXXXXXXXXXXXXXXXXXXXX', 
        'XFFFFFFFFFFFFFFFFFFFX    XFFFFFFFFFFFFFFFFFFFX    XFFFFFFFFFFFFFFFFFFFX',
        'XFFFFFFFFFFFFFFFFFFFX    XFFFFFFFFFFFFFFFFFFFX    XFFFFFaFFFFFFFFFFFFFX',
        'XFFXFFFFFFFFFFFFFFFFXXXXXXFFFFFFFFaFFFFFFFFFFXXXXXXFFFFFFFFFFFFFFFFFFFX',
        'XCFXFFFFFFaFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFD',
        'XFFXFFFFFFFFFFFFFFFFXXXXXXFFFFFFFFFFFaFFFFFFFXXXXXXFFFFFFFFFFFFFFFFFFFX',
        'XFFFFFFFFFFFFFFFFFFFX    XFFFFFFFFFFFFFFFFFFFX    XFFFFFFFFFFFFFFaFFFFX',
        'XFFFFFFFFFFFFFFFFFFFX    XFFFFFFFFFFFFFFFFFFFX    XFFFFFFFFFFFFFFFFFFFX',
        'XXXXXXXXXXXXXXXXXXXXX    XXXXXXXXXXXXXXXXXXXXX    XXXXXXXXXXXXXXXXXXXXX', 
    ]
]
